import {mkdir,writeFile} from 'node:fs/promises';
import {resolve,join} from 'node:path';
import {randomBytes,randomUUID} from 'node:crypto';
const destination = process.argv[2];
if (!destination) throw Error('Usage: node setup.mjs /private/config-directory');
const directory = resolve(destination);
await mkdir(directory,{recursive:true,mode:0o700});
const shared = {pair:'recovery-'+randomUUID(),key:randomBytes(32).toString('hex')};
await writeFile(join(directory,'helper.json'),JSON.stringify({...shared,stateDir:join(directory,'claims'),sshPort:22})+'\n',{flag:'wx',mode:0o600});
await writeFile(join(directory,'controller.json'),JSON.stringify({...shared,listenPort:22222})+'\n',{flag:'wx',mode:0o600});
console.log('Private helper.json and controller.json created; pairing key was not printed');
