#!/usr/bin/env node
'use strict';
// Existing chapter PDF workflow: Chrome + Playwright, selectable text, no art changes.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),cp=require('node:child_process'),assert=require('node:assert/strict');
const {values}=require('node:util').parseArgs({options:{dir:{type:'string'},'playwright-module':{type:'string'},'pdfinfo':{type:'string'},'pdftotext':{type:'string'},'pdfkit-verifier':{type:'string'},help:{type:'boolean'}}});
if(values.help||!values.dir){console.log('Usage: node render.cjs --dir EXTERNAL_PREPARED_DIR [--playwright-module MODULE] [--pdfinfo PATH --pdftotext PATH]\nUses existing Chrome/Playwright. No dependency install, generation, publication or app mutation.');process.exit(values.help?0:2)}
const dir=path.resolve(values.dir),manifest=JSON.parse(fs.readFileSync(path.join(dir,'delivery-manifest.json')));assert.equal(manifest.unpublished,true);const html=fs.readFileSync(path.join(dir,'preview.html'));const sha=b=>crypto.createHash('sha256').update(b).digest('hex');assert.equal(sha(html),manifest.html.sha256);assert.equal(html.length,manifest.html.bytes);assert(!fs.existsSync(path.join(dir,'chapter.pdf')),'Never overwrite an existing PDF');
const normalize=s=>s.normalize('NFKC').replace(/\s+/g,' ').trim();
(async()=>{const pw=require(values['playwright-module']||process.env.PLAYWRIGHT_MODULE||'playwright');const browser=await pw.chromium.launch({channel:'chrome',headless:true});try{const page=await browser.newPage();await page.setContent(html.toString('utf8'),{waitUntil:'load'});const checks=await page.evaluate(async()=>{await document.fonts.ready;await Promise.all([...document.images].map(i=>i.decode()));return {imageCount:document.images.length,imageLoaded:[...document.images].every(i=>i.complete&&i.naturalWidth>0),pages:[...document.querySelectorAll('.page')].map(p=>({height:p.clientHeight,scroll:p.scrollHeight,width:p.clientWidth,scrollWidth:p.scrollWidth})),text:document.body.innerText}});assert(checks.imageLoaded);assert.equal(checks.pages.length,manifest.pageCount);for(const p of checks.pages)assert(p.scroll<=p.height+1&&p.scrollWidth<=p.width+1,'Layout overflow; caption not silently shortened');for(const text of manifest.requiredSelectableText)assert(normalize(checks.text).includes(normalize(text)),'Missing DOM caption');const file=path.join(dir,'chapter.pdf');await page.pdf({path:file,preferCSSPageSize:true,printBackground:true,displayHeaderFooter:false,tagged:true});let pageCount;if(values['pdfkit-verifier']){const proof=JSON.parse(cp.execFileSync('osascript',['-l','JavaScript',values['pdfkit-verifier'],file,path.join(dir,'delivery-manifest.json')],{maxBuffer:8*1024*1024}).toString());assert.equal(proof.selectableTextVerified,true);pageCount=proof.pageCount;}else{const info=cp.execFileSync(values.pdfinfo||'pdfinfo',[file]).toString();pageCount=Number(info.match(/^Pages:\s+(\d+)/m)?.[1]);const extracted=cp.execFileSync(values.pdftotext||'pdftotext',['-layout','-enc','UTF-8',file,'-'],{maxBuffer:8*1024*1024}).toString();for(const text of manifest.requiredSelectableText)assert(normalize(extracted).includes(normalize(text)),'Caption missing from selectable PDF text');}assert.equal(pageCount,manifest.pageCount);const b=fs.readFileSync(file);manifest.pdf={file:'chapter.pdf',sha256:sha(b),bytes:b.length,pageCount,selectableTextVerified:true,imageCount:checks.imageCount,imagesLoaded:true,layoutChecked:true};fs.writeFileSync(path.join(dir,'delivery-manifest.json'),JSON.stringify(manifest,null,2)+'\n');console.log(JSON.stringify(manifest.pdf));}finally{await browser.close()}})().catch(e=>{console.error(e.message);process.exitCode=1});
