"""Author final cast source bindings and exact solo specifications from durable queue."""
import json,hashlib,sys
from pathlib import Path
from cast_ops import DATA as D,RUNTIME as R,Store,atomic_json,rank_reference_pack
S=Path('/Volumes/TB4/mac-mini-storage/shared/pinpin-r17-studio-source')
store=Store(D);state=store.read();assets={a['id']:a for a in state['assets']}
run=json.loads((D/'workflows/cast-run.json').read_text());remaining=[r['id'] for r in run['characters'] if not r.get('complete')]
definitions={
 'squirrel-community':{'name':'Forest squirrel community','images':[('image73.png','chapter-19',13)],'partners':['papa','pinpin','oreshek'],
  'identity':'Recurring unnamed squirrel community: experienced adult advisers/builders and their young are sourced. Show TWO representative proposed designs, not canonical total: one older gray-brown adviser with cream muzzle and one smaller russet youngster with cream belly; tufted ears, bushy tails, squirrel paws, no hedgehog quills. No personal names or precise ages, no inferred sex. Adults capable of planning/building; young age-appropriate play.',
  'basis':'Original chapters19–25 establish advisers, builders and young, with actual image73 showing varied squirrels working with hedgehogs. Group visuals establish diversity, not named individual portraits. Two representative faces/colors/relative sizes are proposed book adaptations.'},
 'migrating-bird-family':{'name':"Pipilini’s migrating family",'images':[('image49.png','chapter-08',0)],'partners':['pipilini','pinpin'],
  'identity':'Recurring unnamed bird family migrates south to Africa each year; old Pipilini used to lead the flock but cannot travel that far now (original chapter8). Show TWO representative capable flying birds, mature-looking larger and smaller companion, not canonical count, sex or asserted parent/chick relationship. Proposed pale rose/cream feather design related to working Pipilini with reddish small beaks, folded feather wings, thin supported feet, long light rose tails. No mammal arms. Pipilini is the separate older weak-winged character, not one of these active flying representatives.',
  'basis':'Original chapter8 block3 establishes family and migration; relative ages within the family, number, species and individual appearance are not specified. Image49 has one unlabeled pale rose bird, not a family portrait. Proposed representative size/role differentiation remains explicitly unsourced; established older Pipilini identity is retained only as counterpart.'},
 'tarin':{'name':'Tarin — two forms, one wizard','images':[('image77.png','chapter-13',15),('image71.png','chapter-13',16)],'partners':['pinpin','pipilini'],
  'identity':'Tarin is a HUMAN WIZARD who deliberately took hedgehog form, returns to tall human form after enchanted coffee, then becomes hedgehog again at sunset (original chapter13 blocks6–10,12). HUMAN: old-looking male wizard, white wavy shoulder-length hair, long white beard and bushy brows, rounded pink nose, small round spectacles, rich gold robe with subtle embroidered trim and brown shoes, actual original image77 identity. HEDGEHOG: proposed elderly salt-and-pepper/gray-brown quills, cream face/chest, white eyebrows and warm brown eyes echoing human form, rounded ears/muzzle, natural two paws/two feet, no human beard or robe. Both depictions are ONE person in alternative forms, never two independent cast members.',
  'basis':'Human/hedgehog transformation is explicit source text. Actual original images77/71 show human wizard in gold robe with white beard/hair; glasses appear in77, not71. These control proposed dimensional human adaptation. No verified Tarin hedgehog portrait: hedgehog pictured beside wizard is a companion, not assumed Tarin. Tarin’s relationship to published hedgehog Elder is unresolved; keep this distinct requirement, do not copy or silently alias published Elder.'}}
cfg=state['project']['book']['characterReferenceDefaults'];bindings=cfg.setdefault('characters',{})
def ref(aid,role):
 a=assets[aid];return {'assetId':aid,'sha256':a['sha256'],'path':str(store.asset_path(aid,store.read())),'role':role}
directions='Front: nose/beak centered toward viewer. Left 3/4: nose/beak SCREEN LEFT, both eyes visible if anatomy permits, torso LEFT. Left profile: true side, nose/beak SCREEN LEFT, torso LEFT. Right 3/4: nose/beak SCREEN RIGHT, both eyes visible if anatomy permits, torso RIGHT. Right profile: true side, nose/beak SCREEN RIGHT, torso RIGHT. Rear: back, face invisible.'
for identifier in remaining:
 d=definitions[identifier];folder=D/'workflows/characters'/identifier;e=json.loads((folder/'evidence.json').read_text());visual=[];sources=[]
 for filename,chapter,block in d['images']:
  p=S/'docs/images'/filename;raw=p.read_bytes();sha=hashlib.sha256(raw).hexdigest();asset=next((a for a in assets.values() if a['sha256']==sha),None)
  role='identity-human-form' if identifier=='tarin' else 'original-visual-context'
  if not asset:asset,_=store.upload_asset(raw,filename,provenance={'sourcePath':str(p),'sourceSha256':sha,'role':role,'inspection':d['basis']},review_status='unreviewed');assets[asset['id']]=asset
  sources.append({'assetId':asset['id'],'sha256':sha,'role':role});visual.append({'path':str(p),'sha256':sha,'chapterId':chapter,'blockIndexZeroBased':block,'inspection':d['basis']})
 binding={'speciesAndRole':d['identity'],'counterpartIds':d['partners'],'designBasis':d['basis'],'sourceReferences':sources};bindings[identifier]=binding
 row=next(r for r in run['characters'] if r['id']==identifier);row['referenceBindings']=binding;row['registeredReferenceIds']=[r['assetId'] for r in sources]
 e.update(character=row,referenceBindings=binding,inspectedVisualEvidence=visual,registeredReferences=[assets[r['assetId']] for r in sources]);atomic_json(folder/'evidence.json',e)
 with (folder/'README.md').open('a') as f:f.write('\n## Working source and proposal distinction\n\n'+d['identity']+'\n\n'+d['basis']+'\n\nExact age: **not stated**. Actual pixel paths/hashes and original text citations are separated in evidence.json. No personal Miguel approval.\n')
 refs=[ref(r['assetId'],'subject-source:'+r['role']) for r in sources]
 refs += [ref(cfg['layoutReference']['assetId'],'layout-direction-only'),ref(state['project']['book']['styleReferenceIds'][0],'book-style')]
 if identifier=='migrating-bird-family':
  p=json.loads((D/'reports/character-packages/pipilini.json').read_text());refs.insert(0,ref(p['stages']['solo']['candidates'][-1]['assetId'],'PRIMARY-working-family-visual-lineage'))
 selected,omitted=rank_reference_pack(refs)
 layout=('LARGE LANDSCAPE DOUBLE-SHEET: human form LEFT, hedgehog form RIGHT, each half FOUR rows of SIX studies, 48 studies total. Each half has FACE VIEWS, EXPRESSIONS, WHOLE BODY VIEWS, NORMAL POSES. Separate form headings, large readable cells, full margin around robe/feet/quills. A small footer diagram HUMAN → HEDGEHOG → HUMAN labels these ALTERNATIVE FORMS OF ONE WIZARD, not two people. Do not put both forms together as separate characters in gestures.' if identifier=='tarin' else 'Portrait page, FOUR rows of SIX readable cells, TWO representative subjects separately distinguishable in EVERY cell. Larger adult/companion and smaller young/companion sizes consistent. No canonical total claimed.')
 prompt=f'Use case: illustration-story. Production reference titled "{d["name"]}" with subtitle "Proposed book adaptation", warm dimensional PinPin book style on ivory. {layout} Subject/source requirements: {d["identity"]} Source distinction: {d["basis"]} Actual inputs ordered: '+', '.join(f'{n+1}: {r["role"]}' for n,r in enumerate(selected))+f'. Layout sheet controls grid/opposed directions ONLY; never copy its species/clothing/anatomy. Row1 FACE VIEWS for each subject/form explicitly: {directions} Row2 EXPRESSIONS: Calm, Curious, Happy, Surprised, Thoughtful, Mild upset, naturally varied. Row3 FULL BODY VIEWS explicitly: {directions} Row4 NORMAL POSES: Sit, Reach, Greet, Carry cup or small nut, Share, Rest. Birds instead Perch, Hop, Sing, Spread wings, Fly gently, Rest. No human hands/arms on birds. Distinct two arms/two legs on human and hedgehog/squirrel, two wings/two feet on birds, clear supported feet/perches. Human full beard/robe hem/shoes visible; hedgehog whole quills/feet visible. Generous margins, no fused limbs, no clipped tails. Concise labels only, no invented ages/heights/names. One real unified image.'
 (folder/'solo-prompt.txt').write_text(prompt);atomic_json(folder/'solo-spec.json',{'entityId':identifier,'stage':'solo','prompt':prompt,'promptFile':str(folder/'solo-prompt.txt'),'outputName':identifier+'-solo.png','references':selected,'omittedReferences':omitted})
state=store.read();project=state['project'];project['book']['characterReferenceDefaults']=cfg
for entity in project['entities']:
 if entity['id'] in remaining:entity.update(referenceIds=[r['assetId'] for r in bindings[entity['id']]['sourceReferences']],identity=bindings[entity['id']]['speciesAndRole'])
store.save_project(project,expected_revision=state['revision']);atomic_json(D/'workflows/cast-run.json',run)
print(json.dumps({'prepared':remaining,'referenceCounts':{i:len(json.loads((D/'workflows/characters'/i/'solo-spec.json').read_text())['references']) for i in remaining}}))
