"""Prepare capped final-group interaction inputs from actual saved stage receipts."""
import json,sys
from cast_ops import DATA as D,Store,rank_reference_pack,atomic_json
store=Store(D);state=store.read();assets={a['id']:a for a in state['assets']}
defaults=state['project']['book']['characterReferenceDefaults']
plans={
 'squirrel-community': '''SIX panels, two columns by three rows. In EVERY panel the two COMMUNITY SQUIRRELS are the larger gray-brown experienced adviser and smaller russet youngster from primary sheet, not hedgehogs. Panel1 Shared ground: both community squirrels, Papa ADULT broad dark-quilled HEDGEHOG, PinPin CHILD copper-quilled HEDGEHOG. Papa roughly adviser adult scale; PinPin and young squirrel peer scale, separate grounded bodies. Panel2 Planning: community adviser SQUIRREL and Elder Oreshek OLD GRAY SQUIRREL (white brows, source sheet), two DIFFERENT identifiable squirrels inspecting a leaf-map while russet youngster listens, no Papa substitution. Panel3 Play: community russet youngster SQUIRREL and PinPin CHILD HEDGEHOG roll a small nut to each other with clearly separate paws. Panel4 Help: Papa ADULT HEDGEHOG and community gray-brown adviser SQUIRREL carry a light branch together, all four paws and shared branch ownership clear; young squirrel watches. Panel5 Welcome: community adviser SQUIRREL kneels and gently side-hugs its young russet SQUIRREL neighbor; young paws visible, grounded feet, no asserted parent/child relationship. PinPin CHILD HEDGEHOG stands nearby smiling. Panel6 Gather: the two community squirrels and distinct Oreshek OLD GRAY SQUIRREL sit together with a basket of nuts, distinct tails and bodies, no invented additional characters.''',
 'migrating-bird-family': '''SIX panels two columns by three rows. PRIMARY sheet's TWO active FAMILY BIRDS: larger rose/cream representative and smaller rose/cream companion, capable flying, no asserted parent/chick or exact age. Pipilini from counterpart sheet is the SEPARATE OLDER pale-rose long-tailed BIRD, gently weathered brows and weak wings, never one of those two active birds. PinPin is CHILD copper-quilled HEDGEHOG. Panel1 Common ground: the two active FAMILY BIRDS perched on a low branch beside standing PinPin CHILD HEDGEHOG; all tails and feet visible, bird bodies small beside child. Panel2 Greeting: three distinct BIRDS, the two active representatives and older Pipilini, on a broad low perch, bills facing each other. PinPin CHILD HEDGEHOG listens on ground. Panel3 Food: PinPin CHILD HEDGEHOG offers seeds in a cupped paw resting close to ground; larger FAMILY BIRD takes one seed with its bill, smaller FAMILY BIRD stands nearby; no wings becoming human arms. Panel4 Gentle contact: larger FAMILY BIRD rests one folded feather wing gently against older Pipilini BIRD on stable branch; smaller FAMILY BIRD observes. Three distinct supported bird bodies, six bird feet, ordinary supported wing touch, not interpenetrating torsos. Panel5 Departure: TWO active FAMILY BIRDS fly together low above ground with anatomical two feather wings each; older Pipilini BIRD stays perched beside PinPin CHILD HEDGEHOG, clearly no strenuous flight for weak-winged elder. Panel6 Quiet company: older Pipilini BIRD rests beside seated PinPin CHILD HEDGEHOG, two active FAMILY BIRDS perch nearby; distinct long rose tails, feet gripping perch, no floating bodies.''',
 'tarin': '''SIX panels, two columns by three rows. Tarin is ONE elderly wizard in ALTERNATIVE forms, never two simultaneous independent people. HUMAN form: old white-haired white-bearded man, small round spectacles, gold robe, brown shoes, natural human hands. HEDGEHOG form: mature elderly gray/salt-pepper quills and WHITE eyebrows from corrected primary sheet, cream muzzle/chest, no human beard/robe/staff. PinPin is CHILD copper-quilled HEDGEHOG, Pipilini OLDER rose/cream long-tailed BIRD with weak wings. Panel1 Human greeting: full-body kneeling HUMAN Tarin listens to standing PinPin CHILD HEDGEHOG, Pipilini BIRD perched low nearby. Human full robe/body fits panel; human naturally much taller than small child, no invented measured height. Panel2 Hedgehog greeting: full-body ADULT elderly HEDGEHOG Tarin stands beside PinPin CHILD HEDGEHOG on same ground; Tarin clearly older/larger than child, white brows and gray quills, Pipilini BIRD perched low nearby. Panel3 Coffee: seated HUMAN Tarin holds one cup with clearly separate HUMAN fingers; PinPin CHILD HEDGEHOG offers a saucer at table edge, Pipilini BIRD perches securely beside them. Cup anatomically supported, hands/paws don't fuse. Panel4 Forest hug: elderly HEDGEHOG Tarin kneels and side-hugs PinPin CHILD HEDGEHOG with two distinct bodies and separate paws/grounded feet; Pipilini BIRD observes, no spines passing through hands. Panel5 Transformation STRIP: THREE sequential separated vignette portraits of SAME Tarin, HEDGEHOG → HUMAN → HEDGEHOG; FIRST arrow labeled Enchanted coffee, SECOND labeled Sunset. It is a time sequence, not three people gathered. Keep forms exactly consistent with panels1/2. Panel6 At sunset: elderly HEDGEHOG Tarin sits with PinPin CHILD HEDGEHOG and Pipilini BIRD at low table, three distinct species/roles, quiet supported posture. No human Tarin simultaneously present. Header 'Two forms, one wizard'. Human-to-hedgehog choice was deliberate originally; enchanted coffee returns him to human, sunset back to hedgehog. Relationship to published Elder remains unresolved, don't copy that Elder.'''}
for identifier in sys.argv[1:]:
 folder=D/'workflows/characters'/identifier
 def ref(aid,role):
  a=assets[aid];return {'assetId':aid,'sha256':a['sha256'],'path':str(store.asset_path(aid,state)),'role':role}
 def solo(entity):
  p=json.loads((D/'reports/character-packages'/(entity+'.json')).read_text())
  candidates=[c for c in p['stages']['solo']['candidates'] if c.get('qaDisposition')!='needs-repair']
  if not candidates:raise ValueError('No current QA-valid solo: '+entity)
  return candidates[-1]['assetId']
 binding=defaults['characters'][identifier]
 refs=[ref(solo(identifier),'PRIMARY-working-identity:verified-solo')]
 refs += [ref(solo(partner),'counterpart-identity:'+partner) for partner in binding['counterpartIds']]
 refs += [ref(state['project']['book']['styleReferenceIds'][0],'book-style:family-relative-scale')]
 sources=[ref(r['assetId'],'source-bibliography-context') for r in binding['sourceReferences']]
 if identifier=='tarin': refs.insert(1,dict(sources[0],role='identity-human-source')) ; sources=sources[1:]
 selected,omitted=rank_reference_pack(refs+sources)
 prompt='Use case: illustration-story. Create a separate readable whole-body cast interaction and scale page titled '+binding.get('title',identifier)+', subtitle Proposed book adaptation. Warm dimensional PinPin book style on ivory, natural expression variation, generous full-body margins and neutral shared-ground/perch contact shadows. ACTUAL INPUTS in order: '+', '.join(str(i+1)+': '+r['role'] for i,r in enumerate(selected))+'. Primary target solo sheet controls TARGET identity, not just style. Every pictured counterpart has its own reference. Family image only supplies book style and relative adult/child scale. Species, age stage and role cannot transfer across characters. '+plans[identifier]+' Source/proposal distinction: '+binding['designBasis']+' No invented precise ages, canonical group totals or names, no merged tails/bodies, no extra limbs, no floating support, no cropped feet/tails/robe. A grounded full-page draft.'
 path=folder/'interactions-prompt.txt';path.write_text(prompt)
 spec={'entityId':identifier,'stage':'interactions','prompt':prompt,'promptFile':str(path),'outputName':identifier+'-interactions.png','references':selected,'omittedReferences':omitted}
 atomic_json(folder/'interactions-spec.json',spec)
 print(json.dumps(spec))
