import {model,onChange,load,save,edit,changed,mutate,upload,poll,chapter,chapterIndex,scene,entity} from './store.js';
import {esc,text,arr,uid,button,asset,put} from './ui.js';
import {renderBook} from './book.js';
import {renderReferences} from './references.js';
import {renderChapter} from './chapter.js';
import {renderTempo} from './tempo.js';
import {renderStoryboard} from './storyboard.js';
import {renderProduction} from './production.js';
import {openPanorama} from './panorama.js';
const stages=[['book','Book','The story beyond a single chapter.'],['references','References','The cast, their places, and the things that stay true.'],['chapter','Chapter','A clear intention, a real action, an earned reaction.'],['tempo','Tempo','Make room for surprise, play, and a breath.'],['storyboard','Storyboard','See the sequence before making every final image.'],['production','Production','Turn a good plan into a version you can review.']];
const views={book:renderBook,references:renderReferences,chapter:renderChapter,tempo:renderTempo,storyboard:renderStoryboard,production:renderProduction};
const app=document.querySelector('#app'),formCache=new Map(),detailCache=new Map();let toastTimer;
function toast(message,error=false){const el=document.querySelector('#toast');el.textContent=message;el.className='visible'+(error?' error':'');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.className='',6500)}
function formKey(f){return model.stage+':'+f.dataset.form+':'+[...f.querySelectorAll('input[type=hidden]')].map(x=>x.name+'='+x.value).join('|')}
function rememberForms(){for(const f of app.querySelectorAll('form[data-form]')){const values={};for(const x of f.elements)if(x.name&&!['file','hidden','submit'].includes(x.type))values[x.name]=x.value;formCache.set(formKey(f),values)}}
function restoreForms(){for(const f of app.querySelectorAll('form[data-form]')){const values=formCache.get(formKey(f));if(values)for(const x of f.elements)if(x.name in values&&!['file','hidden','submit'].includes(x.type))x.value=values[x.name]}rolePreviews()}
function status(){const s=document.querySelector('#save-state');if(s)s.innerHTML=`<span class="status-dot ${model.dirty?'dirty':''}"></span><span>${model.busy?'Saving / working…':model.conflict?'Server changes available':model.dirty?'Unsaved changes':'Saved on the Mini'}<small class="revision"> · revision ${model.revision}</small></span>`;const b=document.querySelector('#save-project');if(b)b.disabled=!model.dirty||model.busy;const note=document.querySelector('#conflict-notice');if(note){note.classList.toggle('hide',!model.conflict);note.querySelector('p').textContent=model.notice}}
function render(reason){if(!model.draft)return;if(reason==='status'||reason==='metadata'){status();return}rememberForms();for(const [i,d] of [...app.querySelectorAll('details')].entries())detailCache.set((app.dataset.stage||model.stage)+':'+i+':'+d.querySelector('summary')?.textContent,d.open);const current=stages.find(s=>s[0]===model.stage),c=chapter();
 app.innerHTML=`<div class="app-shell"><aside class="sidebar"><div class="brand"><span class="brand-name">Mr. PinPin</span><small>Story Studio</small></div><nav class="stage-nav" aria-label="Authoring stages">${stages.map(([id,label],i)=>`<button data-action="stage" data-id="${id}" class="${model.stage===id?'active':''}" ${model.stage===id?'aria-current="page"':''}><span class="stage-number">0${i+1}</span>${label}</button>`).join('')}</nav><div class="sidebar-bottom"><strong>A place to make the story.</strong>Work is saved locally on the Mini.<br>Publishing is always separate.</div></aside><div class="workspace"><header class="topbar"><div class="breadcrumbs">${esc(model.draft.name||'Mr. PinPin')} <span> / </span><strong>${current[1]}</strong></div><div class="flags" aria-label="Content language"><small>Content</small>${[['ru','🇷🇺','Russian'],['en','🇬🇧','English'],['es','🇪🇸','Spanish']].map(([code,flag,label])=>`<button data-action="language" data-id="${code}" aria-label="${label} content" aria-pressed="${model.lang===code}" title="${label} content">${flag}</button>`).join('')}</div></header><main class="content"><div class="page-heading"><div><span class="eyebrow">THE PINPIN WORKSHOP · ${current[1]}</span><h1>${current[1]==='Book'?'Every good story starts somewhere.':current[1]}</h1><p>${current[2]}</p></div><div class="heading-tools">${!['book','references'].includes(model.stage)?`<label class="field"><span>Working chapter</span><select id="chapter-select" aria-label="Working chapter">${arr(model.draft.chapters).map(x=>`<option value="${esc(x.id)}" ${x.id===c?.id?'selected':''}>${esc(text(x.title,model.lang)||'Untitled chapter')}</option>`).join('')}</select></label>${button('+ Chapter','new-chapter','','small')}`:''}</div></div><section id="conflict-notice" class="notice ${model.conflict?'':'hide'}"><p>${esc(model.notice)}</p><div class="row">${button('Download my draft','download-draft','','small')}${button('Load server version','reload','','small')}</div></section>${views[model.stage]()}</main></div><footer class="savebar"><div id="save-state" class="save-status"></div><div class="actions">${button('Refresh','reload','','quiet')}<button id="save-project" class="primary" data-action="save">Save changes</button></div></footer></div>`;
 restoreForms();app.dataset.stage=model.stage;for(const [i,d] of [...app.querySelectorAll('details')].entries()){const k=model.stage+':'+i+':'+d.querySelector('summary')?.textContent;if(detailCache.has(k))d.open=detailCache.get(k)}status();if(model.busy)disable();
}
function disable(){document.body.classList.add('busy');for(const x of app.querySelectorAll('button,input,textarea,select')){x.dataset.preDisabled=x.disabled?'1':'0';x.disabled=true}}
function enable(){document.body.classList.remove('busy');for(const x of app.querySelectorAll('[data-pre-disabled]')){x.disabled=x.dataset.preDisabled==='1';delete x.dataset.preDisabled}status()}
async function run(fn,message){if(model.busy)return;model.busy=true;disable();status();try{await fn();if(message)toast(message)}catch(e){console.error(e);toast(e.message,true)}finally{model.busy=false;enable();render()}}
function downloadDraft(){const url=URL.createObjectURL(new Blob([JSON.stringify(model.draft,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='pinpin-studio-draft.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function move(list,id,delta){const i=list.findIndex(x=>x.id===id),j=i+delta;if(i<0||j<0||j>=list.length)return;[list[i],list[j]]=[list[j],list[i]];changed()}
function modal(title,body){const wrap=document.createElement('div');wrap.className='modal-backdrop';wrap.innerHTML=`<section class="modal" role="dialog" aria-modal="true" aria-label="${esc(title)}"><div class="panel-header"><h2>${esc(title)}</h2>${button('Close','close-modal','','quiet')}</div>${body}</section>`;document.body.append(wrap);wrap.querySelector('input,textarea,select,button')?.focus();wrap.addEventListener('click',e=>{if(e.target===wrap||e.target.closest('[data-action="close-modal"]'))wrap.remove()});wrap.addEventListener('keydown',e=>{if(e.key==='Escape')wrap.remove()});return wrap}
function newChapter(){const m=modal('A new chapter',`<form id="new-chapter-form"><label class="field"><span>Chapter title · ${model.lang.toUpperCase()}</span><input name="title" required autofocus placeholder="What is this part of the story called?"></label><label class="field"><span>In a sentence, what happens?</span><textarea name="synopsis" rows="3"></textarea></label><button class="primary">Create chapter</button></form>`);m.querySelector('form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),id=uid('chapter'),title={en:'',ru:'',es:''};title[model.lang]=f.get('title');model.draft.chapters.push({id,title,synopsis:f.get('synopsis'),script:'',scenes:[],coverAssetId:null});model.chapterId=id;model.draft.activeChapterId=id;model.sceneId=null;model.stage='chapter';m.remove();changed();toast('Chapter added. Save to keep it on the Mini.')};}
function newReference(){const id=uid('reference');model.draft.entities.push({id,name:'New reference',kind:model.referenceKind==='all'?'character':model.referenceKind,description:'',identity:'',scale:'',geometry:'',referenceIds:[],reviewStatus:'draft'});model.entityId=id;model.query='';changed()}
function newScene(){const c=chapter();if(!c)return toast('Create a chapter first.',true);const id=uid('scene');c.scenes.push({id,title:'New story beat',captions:{en:'',ru:'',es:''},action:'',dependsOn:[],castIds:[],locationId:null,propIds:[],camera:{position:'',height:'',yaw:null,pitch:null,fov:null,gaze:''},stateBefore:'',stateAfter:'',tempo:{activity:1,comedy:1,discovery:1},imageAssetId:null,status:'draft',blocking:[]});model.sceneId=id;changed()}
function jobById(id){return arr(model.server.jobs).find(j=>j.id===id)}
app.addEventListener('input',e=>{const x=e.target;if(model.busy)return;if(x.matches('[data-path]')){let v=x.value;if(x.multiple)v=[...x.selectedOptions].map(o=>o.value);else if(x.dataset.list)v=v.split(',').map(s=>s.trim()).filter(Boolean);else if(x.dataset.number)v=v===''?null:Number(v);if(x.tagName==='SELECT'&&!v)v=null;edit(x.dataset.path,v)}else if(x.matches('[data-array-path]')){const v=[...app.querySelectorAll('[data-array-path]')].filter(a=>a.dataset.arrayPath===x.dataset.arrayPath&&a.checked).map(a=>a.value);edit(x.dataset.arrayPath,v)}else if(x.id==='reference-search'){model.query=x.value;const pos=x.selectionStart;render();const y=document.querySelector('#reference-search');y.focus();y.setSelectionRange(pos,pos)}});
function rolePreviews(){for(const s of app.querySelectorAll('[data-role-picker]')){const img=s.parentElement.querySelector('img'),url=s.selectedOptions[0]?.dataset.url;img.classList.toggle('hide',!url);if(url)img.src=url}const kind=app.querySelector('#job-kind');if(kind)app.querySelector('#cubemap-fields')?.classList.toggle('hide',kind.value!=='cubemap')}
app.addEventListener('change',e=>{const x=e.target;if(x.id==='chapter-select'){model.chapterId=x.value;model.sceneId=null;model.boardId=null;model.pageId=null;model.panelId=null;render()}if(x.id==='board-select'){model.boardId=x.value;model.pageId=null;model.panelId=null;render()}if(x.id==='page-select'){model.pageId=x.value;model.panelId=null;render()}if(x.id==='job-kind'||x.matches('[data-role-picker]'))rolePreviews()});
app.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b||model.busy)return;const a=b.dataset.action,id=b.dataset.id;
 if(a==='stage'){rememberForms();model.stage=id;render();window.scrollTo(0,0)}
 else if(a==='language'){model.lang=id;localStorage.setItem('pinpin-studio-language',id);render()}
 else if(a==='save')run(save,'Saved on the Mini.');
 else if(a==='reload'){if(model.dirty&&!confirm('Load the server version and discard these unsaved edits? You can download your draft first.'))return;run(load,'Loaded the latest saved project.')}
 else if(a==='download-draft')downloadDraft();
 else if(a==='new-chapter')newChapter();
 else if(a==='open-chapter'){model.chapterId=id;model.sceneId=null;model.stage='chapter';render()}
 else if(a==='chapter-up'||a==='chapter-down')move(model.draft.chapters,id,a.endsWith('up')?-1:1);
 else if(a==='new-reference')newReference();
 else if(a==='edit-reference'){model.entityId=id;render();window.scrollTo({top:0,behavior:'smooth'})}
 else if(a==='close-reference'){model.entityId=null;render()}
 else if(a==='reference-filter'){model.referenceKind=id;model.entityId=null;render()}
 else if(a==='detach-reference'){const [eid,aid]=id.split('|'),ent=model.draft.entities.find(x=>x.id===eid);ent.referenceIds=ent.referenceIds.filter(x=>x!==aid);changed()}
 else if(a==='new-scene')newScene();
 else if(a==='select-scene'){model.sceneId=id;render()}
 else if(a==='scene-up'||a==='scene-down')move(chapter().scenes,id,a.endsWith('up')?-1:1);
 else if(a==='remove-scene'){if(!confirm('Remove this beat and its dependency links from the draft?'))return;const c=chapter();c.scenes=c.scenes.filter(s=>s.id!==id);for(const s of c.scenes)s.dependsOn=arr(s.dependsOn).filter(x=>x!==id);model.sceneId=null;changed()}
 else if(a==='queue-scene'){model.queueSceneId=id;model.jobKind=scene()?.imageAssetId?'edit':'illustration';model.stage='production';render();window.scrollTo(0,0)}
 else if(a==='select-panel'){model.panelId=id||null;render();document.querySelector('.storyboard-controls')?.scrollIntoView({block:'center',behavior:'smooth'})}
 else if(a==='approve-artifact'||a==='reject-artifact'){const [jobId,artifactId]=id.split('|');run(()=>mutate('/api/jobs/'+encodeURIComponent(jobId)+'/review',{decision:a==='approve-artifact'?'approve':'reject',feedback:'',artifactId}),a==='approve-artifact'?'Approved for this local project. Nothing has been published.':'Candidate rejected; original retained.')}
 else if(a==='use-text'){const [jid,aid]=id.split('|'),t=jobById(jid)?.artifacts?.find(x=>x.id===aid),c=chapter();if(!c)return toast('Choose a chapter first.',true);if(c.script&&!confirm('Replace this chapter’s draft script with the candidate text?'))return;c.script=t?.text||'';model.stage='chapter';changed();toast('Candidate placed in the script. Review it, then Save.')}
 else if(a==='open-asset'){const url=asset(model.server,id)?.url;if(url)window.open(url,'_blank','noopener')}
 else if(a==='panorama'){const ref=asset(model.server,id);if(ref)openPanorama(ref)}
 else if(a==='remove-chapter'){const c=chapter();if(!c||!confirm('Remove this chapter from the local authoring project? Published books are unaffected.'))return;model.draft.chapters=model.draft.chapters.filter(x=>x.id!==c.id);model.chapterId=model.draft.chapters[0]?.id||null;model.draft.activeChapterId=model.chapterId;model.sceneId=null;changed()}
 else if(a==='add-blocking'){const s=scene();s.blocking||=[];const available=arr(s.castIds).find(id=>!s.blocking.some(x=>x.characterId===id));s.blocking.push({characterId:available||s.castIds?.[0]||'',position:'',action:'',gazeTarget:''});changed()}
 else if(a==='remove-blocking'){scene().blocking.splice(Number(id),1);changed()}
});
app.addEventListener('submit',e=>{const f=e.target;if(!f.dataset.form)return;e.preventDefault();const fd=new FormData(f),data=Object.fromEntries(fd),kind=f.dataset.form,key=formKey(f),decision=e.submitter?.value||'feedback';
run(async()=>{
 if(kind==='instruction'){await mutate('/api/jobs',{kind:'story-plan',chapterId:data.chapterId||chapter()?.id||null,sceneIds:[],instruction:`Stage: ${data.stage}\n\n${data.instruction}`});toast('Instruction saved. Waiting for Codex.')}
 if(kind==='upload-reference'){const a=await upload(fd.get('file')),ent=model.draft.entities.find(x=>x.id===data.entityId);ent.referenceIds=[...new Set([...arr(ent.referenceIds),a.id])];changed();await save();toast('Original image uploaded and attached.')}
 if(kind==='attach-reference'){const ent=model.draft.entities.find(x=>x.id===data.entityId);ent.referenceIds=[...new Set([...arr(ent.referenceIds),data.assetId])];changed();await save();toast('Reference attached.')}
 if(kind==='create-storyboard'){const c=chapter();if(!c?.scenes?.length)throw new Error('Add at least one story beat first.');const r=await mutate('/api/storyboards',{chapterId:c.id,panelsPerPage:Number(data.panelsPerPage),language:model.lang});model.boardId=r.storyboard.id;model.pageId=null;model.panelId=null;toast('Storyboard PNG pages are ready.')}
 if(kind==='board-feedback'){const board=model.server.storyboards.find(x=>x.id===data.boardId),page=board.pages.find(x=>x.id===data.pageId);if(['feedback','revision'].includes(decision)&&!data.feedback.trim())throw new Error('Write a note before sending feedback.');await mutate('/api/storyboards/'+encodeURIComponent(data.boardId)+'/review',{pageId:data.pageId,sceneId:data.sceneId||undefined,decision:decision==='revision'?'feedback':decision,feedback:data.feedback});if(decision==='revision'){await mutate('/api/jobs',{kind:'edit',chapterId:chapter().id,sceneIds:data.sceneId?[data.sceneId]:page.panels.map(p=>p.sceneId),instruction:'Storyboard revision request:\n'+data.feedback,referenceBindings:[{assetId:page.assetId,role:'storyboard-layout'}]});toast('Feedback saved and revision queued for Codex.')}else toast('Storyboard review saved.')}
 if(kind==='generation'){const bindings=[];if(data.kind==='cubemap'){if(!data.panoramaAssetId||!data.locationAssetId||data.panoramaAssetId===data.locationAssetId)throw new Error('Choose two different images: the successful panorama and the new location.');bindings.push({assetId:data.panoramaAssetId,role:'seamless-panorama'},{assetId:data.locationAssetId,role:'location-identity'})}await mutate('/api/jobs',{kind:data.kind,chapterId:chapter()?.id||null,sceneIds:data.sceneId?[data.sceneId]:[],entityId:data.entityId||undefined,instruction:data.instruction,referenceBindings:bindings});model.queueSceneId=null;toast('Request saved with its references. Waiting for Codex.')}
 if(kind==='job-feedback'){const job=jobById(data.jobId);await mutate('/api/jobs/'+encodeURIComponent(data.jobId)+'/review',{decision:'feedback',feedback:data.feedback});if(decision==='revision'){const latest=arr(job.artifacts).filter(a=>a.type==='image').at(-1),refs=arr(job.referenceBindings).map(({assetId,role,entityId})=>({assetId,role,entityId}));if(latest)refs.push({assetId:latest.assetId,role:'edit-target'});await mutate('/api/jobs',{kind:latest?'edit':job.kind,chapterId:job.chapterId,sceneIds:job.sceneIds,entityId:job.entityId||undefined,instruction:`Revise the previous result.\n\n${data.feedback}\n\nPrevious instruction:\n${job.instruction}`,referenceBindings:refs});toast('Feedback saved; next version queued for Codex.')}else toast('Feedback saved beside this request.')}
 formCache.delete(key);for(const current of app.querySelectorAll('form[data-form]'))if(formKey(current)===key)current.reset();
});
});
onChange(render);window.addEventListener('beforeunload',e=>{if(model.dirty){e.preventDefault();e.returnValue=''}});
load().catch(e=>{app.innerHTML=`<main class="loading"><h1>The Studio could not connect.</h1><p>${esc(e.message)}</p><button onclick="location.reload()">Try again</button></main>`});setInterval(poll,15000);
