import {model,chapter,chapterIndex,scene} from './store.js';
import {esc,text,field,button,picture,instruction,empty,arr,select,asset,chips} from './ui.js';
export function renderChapter(){const c=chapter();if(!c)return empty('Your next chapter starts here','Use “New chapter” to create a script and its first story beats.');const ci=chapterIndex(),base=`chapters.${ci}`,s=scene();
 return `<section class="panel" style="margin-bottom:22px"><div class="fields">${field('Chapter title · '+model.lang.toUpperCase(),base+'.title.'+model.lang,c.title?.[model.lang])}${field('What happens in this chapter?',base+'.synopsis',c.synopsis)}${field('Chapter script',base+'.script',c.script,{area:true,rows:6,wide:true,placeholder:'Write the full story first. Break it into beats below when you are ready.'})}</div><details><summary>Chapter settings</summary>${field('Stable chapter ID',base+'.id',c.id,{readonly:true})}${button('Remove chapter from project','remove-chapter',c.id,'small danger')}</details></section><div class="panel-header"><div><h2>The story, beat by beat</h2><p>Give each image an action, a reason, and a place in the sequence.</p></div>${button('+ Story beat','new-scene','','primary')}</div><div class="editor-layout"><aside class="scene-list" aria-label="Story beats">${arr(c.scenes).map((x,i)=>`<button data-action="select-scene" data-id="${esc(x.id)}" class="${x.id===s?.id?'active':''}"><span class="scene-number">${i+1}</span>${x.imageAssetId?`<img src="${esc(asset(model.server,x.imageAssetId)?.url||'')}" alt="">`:''}<span><strong>${esc(x.title||x.id)}</strong><small>${esc(x.status||'draft')}</small></span></button>`).join('')||'<p class="muted">No beats yet.</p>'}</aside>${s?renderScene(s,c,base):empty('Room for the first beat','Add a moment: an intention, an action, a surprise, or a breath.')}</div>${instruction('Chapter',c.id)}`;
}
function renderScene(s,c,base){const i=c.scenes.findIndex(x=>x.id===s.id),p=`${base}.scenes.${i}`,entities=arr(model.draft.entities),options=kind=>entities.filter(e=>e.kind===kind).map(e=>({id:e.id,name:e.name}));
 return `<section class="panel"><div class="scene-heading"><div><span class="eyebrow">BEAT ${i+1} OF ${c.scenes.length}</span><h2>${esc(s.title||s.id)}</h2></div><div class="row">${button('↑','scene-up',s.id,'small')}${button('↓','scene-down',s.id,'small')}${button('Remove','remove-scene',s.id,'small quiet danger')}</div></div>${picture(model.server,s.imageAssetId,s.title,'scene-preview')}<div class="fields">${field('Beat title',p+'.title',s.title)}${field('Read-aloud text · '+model.lang.toUpperCase(),p+'.captions.'+model.lang,text(s.captions?.[model.lang]),{area:true,rows:3,wide:true})}${field('What are they actually doing?',p+'.action',s.action,{area:true,wide:true,placeholder:'A concrete action and where the characters are looking.'})}${chips('Characters',p+'.castIds',s.castIds,entities.filter(e=>e.kind==='character'),model.server)}${select('Location',p+'.locationId',s.locationId,options('location'),{empty:true})}</div><details><summary>Camera and continuity</summary><div class="fields">${field('Stable ID',p+'.id',s.id,{readonly:true})}${field('Camera / framing',p+'.camera.position',s.camera?.position,{placeholder:'Child-height close-up, over Papa’s shoulder…'})}${field('Height',p+'.camera.height',s.camera?.height)}${field('Yaw',p+'.camera.yaw',s.camera?.yaw,{numeric:true})}${field('Pitch',p+'.camera.pitch',s.camera?.pitch,{numeric:true})}${field('Field of view',p+'.camera.fov',s.camera?.fov,{numeric:true})}${field('Eye lines / attention',p+'.camera.gaze',s.camera?.gaze)}${field('State before',p+'.stateBefore',s.stateBefore,{area:true,placeholder:'One empty bucket; Papa and Scooby outside.'})}${field('State after',p+'.stateAfter',s.stateAfter,{area:true,placeholder:'One full bucket rests on a dry rock.'})}${select('Props',p+'.propIds',s.propIds,options('prop'),{multiple:true})}${select('Because of these earlier beats',p+'.dependsOn',s.dependsOn,c.scenes.filter(x=>x.id!==s.id).map(x=>({id:x.id,name:(x.title||x.id)+' · '+x.id})),{multiple:true})}</div></details>${renderBlocking(s,p,entities)}<details><summary>Use an existing draft image</summary><p>Selecting an existing image updates this local draft after Save. Candidate approvals retain review history in Production.</p>${select('Image',p+'.imageAssetId',s.imageAssetId,arr(model.server.assets).map(a=>({id:a.id,name:a.name})),{empty:true})}</details><div class="form-actions">${button('Request an illustration','queue-scene',s.id,'primary')}${button('Open production','stage','production','quiet')}</div></section>`;
}

function renderBlocking(s,p,entities){const opts=entities.filter(e=>e.kind==='character').map(e=>({id:e.id,name:e.name}));return `<details><summary>Character positions, actions, and eye lines</summary><p>Give each visible character a physical action and a clear focus.</p>${arr(s.blocking).map((b,i)=>`<div class="blocking-row"><div class="fields">${select('Character',p+'.blocking.'+i+'.characterId',b.characterId,opts,{empty:true})}${field('Position in the scene',p+'.blocking.'+i+'.position',b.position)}${field('Action / pose',p+'.blocking.'+i+'.action',b.action)}${field('Looking toward',p+'.blocking.'+i+'.gazeTarget',b.gazeTarget)}</div>${button('Remove blocking row','remove-blocking',String(i),'small quiet')}</div>`).join('')}${button('+ Character blocking','add-blocking','','small')}</details>`;}
