import {studio,esc,words,title,request,post,chapter,asset,caption,active,notify,refresh} from './conversation-state.js';
import {renderWorkspace,renderWorkspaceHeader,selectContext} from './workspace.js';
let conversationKey='',polling=false,connectionFailed=false;
function shell(){document.querySelector('#studio').innerHTML=`<div class="studio-shell" data-mobile="story"><header class="masthead"><div class="brand"><span class="brand-mark">p</span><span class="brand-name">PinPin<span class="brand-subtitle">STORY STUDIO</span></span></div><div class="masthead-right"><span class="connection" id="connection">Connected to your studio</span><a href="/legacy.html" class="legacy-link" target="_blank" rel="noopener">Full editor ↗</a><div class="mobile-switch" aria-label="Mobile view"><button data-mobile="chat">Conversation</button><button data-mobile="story" class="selected">Story</button></div></div></header><main class="split"><section class="conversation-pane" aria-label="Conversation"><div class="conversation-heading"><div><span class="eyebrow">A little imagination, together</span><h1>Your story starts here.</h1></div><span class="little-star" aria-hidden="true">✳</span></div><div class="conversation-scroll" id="messages" role="log" aria-label="Conversation history"></div><div class="turn-status" id="turn-status" aria-live="polite"></div><div class="composer-wrap"><div class="context-strip" id="context-strip"></div><form id="composer" class="composer"><textarea id="message-input" aria-label="Message" placeholder="What shall we make happen next?" rows="3"></textarea><div class="composer-actions"><label class="attach-label">＋ Add an image<input id="attachment" type="file" accept="image/png,image/jpeg,image/webp" aria-label="Attach an image"></label><button type="button" id="interrupt" class="quiet hidden">Stop</button><button id="send" class="primary send">Send ↗</button></div></form><p class="composer-footnote">Drafts stay in the studio. Publishing is always a separate step.</p></div></section><section class="workspace-pane" aria-label="Story workspace"><div id="workspace-header"></div><div class="workspace-content" id="workspace-content"></div></section></main></div>`;
 const input=document.querySelector('#message-input');input.value=sessionStorage.getItem('pinpin-conversation-draft')||'';input.addEventListener('input',()=>{sessionStorage.setItem('pinpin-conversation-draft',input.value);updateControls()});input.addEventListener('keydown',e=>{if(e.key==='Enter'&&(e.metaKey||e.ctrlKey)){e.preventDefault();document.querySelector('#composer').requestSubmit()}});
 document.querySelector('#composer').addEventListener('submit',send);document.querySelector('#interrupt').onclick=interrupt;document.querySelector('#attachment').onchange=upload;
 document.querySelectorAll('[data-mobile]').forEach(b=>{if(b.tagName==='BUTTON')b.onclick=()=>showMobile(b.dataset.mobile)});
 renderConversation();renderWorkspaceHeader();renderWorkspace();renderContext();updateControls();
}
export function showMobile(mode){document.querySelector('.studio-shell').dataset.mobile=mode;document.querySelectorAll('.mobile-switch button').forEach(b=>b.classList.toggle('selected',b.dataset.mobile===mode))}
export function compose(text){document.querySelector('#message-input').value=text;sessionStorage.setItem('pinpin-conversation-draft',text);showMobile('chat');document.querySelector('#message-input').focus();updateControls()}
function contextLabels(context){const labels=[];if(context?.sceneIds?.length)labels.push(context.sceneIds.length+' selected panel'+(context.sceneIds.length>1?'s':''));if(context?.entityId){labels.push(studio.state.project.entities.find(e=>e.id===context.entityId)?.name||'Reference')}return labels}
function renderConversation(){
 const container=document.querySelector('#messages'),messages=studio.conversation?.messages||[],key=JSON.stringify(messages);if(key!==conversationKey||!container.children.length){const bottom=container.scrollHeight-container.scrollTop-container.clientHeight<90;const oldScroll=container.scrollTop;conversationKey=key;container.innerHTML=messages.length?messages.map(m=>`<article class="message ${m.role==='user'?'user':'assistant'}" data-message-id="${esc(m.id)}"><div class="message-label"><span>${m.role==='user'?'You':'Studio · Codex'}</span><span>${m.status==='streaming'?'Writing…':m.status==='error'?'Failed':m.status==='interrupted'?'Interrupted':''}</span></div><div class="message-text">${esc(m.text||'')}</div>${contextLabels(m.context).length||m.context?.assetIds?.length?`<div class="message-context">${contextLabels(m.context).map(t=>'<span>'+esc(t)+'</span>').join('')}${(m.context?.assetIds||[]).map(id=>{const a=asset(id);return a?`<img src="${esc(a.url)}" alt="${esc(a.name)}">`:''}).join('')}</div>`:''}</article>`).join(''):`<div class="welcome"><h2>Small moments.<br>Wonderful stories.</h2><p>Shape the next chapter with your creative partner. Talk through an idea, choose a panel, or bring a character into the conversation.</p><div class="suggestions"><button class="suggestion" data-prompt="Help me plan the next chapter. Start by asking what I have in mind.">Let's shape a story <span>↗</span></button><button class="suggestion" data-prompt="Read this chapter and suggest where we could give the story more room to breathe. Propose a plan before changing anything.">Look at the rhythm <span>↗</span></button><button class="suggestion" data-prompt="Help me develop a character, keeping their existing references in mind.">Explore a character <span>↗</span></button></div></div>`;container.querySelectorAll('[data-prompt]').forEach(b=>b.onclick=()=>compose(b.dataset.prompt));container.scrollTop=bottom?container.scrollHeight:oldScroll}
 const c=studio.conversation,status=document.querySelector('#turn-status');const error=c?.error?.message;let progress='';if(active())progress=`<div class="activity"><span class="activity-dot"></span>${c.status==='connecting'?'Connecting to Codex…':c.status==='interrupting'?'Stopping the current turn…':'Codex is working…'}</div>`;if(Array.isArray(c?.plan)&&active())progress+=c.plan.map(p=>'<div>'+esc(p.step||p.text||p.title||'')+'</div>').join('');status.innerHTML=progress+(error?'<div class="turn-error">'+esc(error)+'</div>':'');updateControls();
}
function updateControls(){const send=document.querySelector('#send');if(!send)return;send.disabled=studio.pending||studio.uploading||active()||!document.querySelector('#message-input').value.trim();send.textContent=studio.pending?'Sending…':studio.uploading?'Uploading…':'Send ↗';const stop=document.querySelector('#interrupt');stop.classList.toggle('hidden',!active());stop.disabled=studio.conversation?.status==='interrupting';document.querySelector('#attachment').disabled=studio.uploading||studio.pending}
export function renderContext(){const strip=document.querySelector('#context-strip');if(!strip)return;const chips=[];for(const id of studio.sceneIds){const s=chapter()?.scenes.find(s=>s.id===id);if(s)chips.push({type:'scene',id,label:'Panel '+(chapter().scenes.indexOf(s)+1),asset:asset(s.imageAssetId)})}if(studio.entityId){const e=studio.state.project.entities.find(e=>e.id===studio.entityId);if(e)chips.push({type:'entity',id:e.id,label:e.name,asset:asset(e.referenceIds?.[0])})}for(const id of studio.assetIds){const a=asset(id);if(a)chips.push({type:'asset',id,label:a.name,asset:a})}strip.innerHTML=chips.map(c=>`<div class="context-chip">${c.asset?`<img src="${esc(c.asset.url)}" alt="">`:''}<span>${esc(c.label)}</span><button type="button" data-remove="${c.type}" data-id="${esc(c.id)}" aria-label="Remove ${esc(c.label)} from context">×</button></div>`).join('');strip.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{if(b.dataset.remove==='scene')studio.sceneIds=studio.sceneIds.filter(id=>id!==b.dataset.id);if(b.dataset.remove==='entity')studio.entityId=null;if(b.dataset.remove==='asset')studio.assetIds=studio.assetIds.filter(id=>id!==b.dataset.id);renderContext();renderWorkspace()})}
async function send(event){event.preventDefault();const input=document.querySelector('#message-input'),text=input.value.trim();if(!text||studio.pending||active())return;studio.pending=true;updateControls();try{const result=await post('/api/conversation/messages',{text,chapterId:studio.chapterId,sceneIds:studio.sceneIds,entityId:studio.entityId,assetIds:studio.assetIds});studio.conversation=result.conversation;if(input.value.trim()===text){input.value='';sessionStorage.removeItem('pinpin-conversation-draft')}renderConversation();document.querySelector('#messages').scrollTop=document.querySelector('#messages').scrollHeight}catch(e){notify(e.message)}finally{studio.pending=false;updateControls()}}
async function interrupt(){try{studio.conversation=(await post('/api/conversation/interrupt',{})).conversation;renderConversation()}catch(e){notify(e.message)}}
async function upload(event){const file=event.target.files[0];if(!file)return;if(studio.assetIds.length>=12){notify('A conversation can include up to 12 attached images.');return}studio.uploading=true;updateControls();try{const data=await request('/api/assets',{method:'POST',headers:{'Content-Type':file.type,'X-File-Name':encodeURIComponent(file.name)},body:file});await refresh();studio.assetIds.push(data.asset.id);renderContext();notify('Image attached to your next message.')}catch(e){notify(e.message)}finally{event.target.value='';studio.uploading=false;updateControls()}}
async function poll(){if(polling)return;polling=true;try{const data=await request('/api/conversation');studio.conversation=data.conversation;renderConversation();if(connectionFailed){document.querySelector('#connection').textContent='Connected to your studio';document.querySelector('#connection').classList.remove('offline');connectionFailed=false}}catch(e){connectionFailed=true;const c=document.querySelector('#connection');c.textContent='Conversation unavailable';c.classList.add('offline');if(!studio.conversation)document.querySelector('#turn-status').innerHTML='<div class="turn-error">Conversation is unavailable. Your draft is safe; retry shortly.</div>'}finally{polling=false}}
async function pollState(){try{const next=await request('/api/state');if(next.revision!==studio.state.revision){const projectChanged=JSON.stringify(next.project)!==JSON.stringify(studio.state.project);studio.state=next;renderContext();if(projectChanged&&!studio.planOpen){renderWorkspaceHeader();renderWorkspace({preserveScroll:true})}}}catch{}}
async function start(){try{await refresh();shell();await poll();setInterval(poll,1300);setInterval(pollState,6000)}catch(e){document.querySelector('#studio').innerHTML='<div class="opening">Your studio could not open.<p class="muted">'+esc(e.message)+'</p><button onclick="location.reload()">Try again</button></div>'}}
start();
