export function openPanorama(asset){
 const root=document.createElement('div');root.className='modal-backdrop panorama-backdrop';root.innerHTML='<section class="panorama-dialog" role="dialog" aria-modal="true" aria-label="Look around panorama"><header><div><strong>Look around</strong><small>Drag to turn · scroll to zoom · Esc to close</small></div><button type="button">Close</button></header><canvas aria-label="Interactive 360 degree panorama" tabindex="0"></canvas><p class="panorama-error" hidden></p></section>';document.body.append(root);
 const canvas=root.querySelector('canvas'),gl=canvas.getContext('webgl',{alpha:false,antialias:true});let texture,program,buffer,closed=false,yaw=0,pitch=0,fov=75,drag=null;
 function close(){closed=true;observer?.disconnect();window.removeEventListener('keydown',key);if(gl){if(texture)gl.deleteTexture(texture);if(program)gl.deleteProgram(program);if(buffer)gl.deleteBuffer(buffer)}root.remove()}
 root.querySelector('button').onclick=close;root.onclick=e=>{if(e.target===root)close()};const key=e=>{if(e.key==='Escape')close();if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();yaw+=(e.key==='ArrowLeft'?-.12:e.key==='ArrowRight'?.12:0);pitch=Math.max(-1.45,Math.min(1.45,pitch+(e.key==='ArrowUp'?.1:e.key==='ArrowDown'?-.1:0)));draw()}};window.addEventListener('keydown',key);
 const observer=new ResizeObserver(()=>draw());observer.observe(canvas);
 function fail(message){const p=root.querySelector('p');p.hidden=false;p.textContent=message}
 if(!gl){fail('This browser could not open the interactive viewer. Open the full image instead.');return}
 const vs='attribute vec2 p; varying vec2 uv;void main(){uv=p;gl_Position=vec4(p,0.,1.);}';
 const fs='precision mediump float; varying vec2 uv;uniform sampler2D image;uniform float aspect,yaw,pitch,fov;void main(){vec3 d=normalize(vec3(uv.x*aspect*tan(fov*.5),uv.y*tan(fov*.5),-1.));float cp=cos(pitch),sp=sin(pitch);d=vec3(d.x,cp*d.y-sp*d.z,sp*d.y+cp*d.z);float cy=cos(yaw),sy=sin(yaw);d=vec3(cy*d.x+sy*d.z,d.y,-sy*d.x+cy*d.z);vec2 t=vec2(.5+atan(d.x,-d.z)/6.2831853,.5-asin(clamp(d.y,-1.,1.))/3.14159265);gl_FragColor=texture2D(image,t);}';
 function shader(type,source){const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error('Panorama shader unavailable');return s}
 try{program=gl.createProgram();const v=shader(gl.VERTEX_SHADER,vs),f=shader(gl.FRAGMENT_SHADER,fs);gl.attachShader(program,v);gl.attachShader(program,f);gl.linkProgram(program);gl.deleteShader(v);gl.deleteShader(f);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error('Panorama viewer unavailable');gl.useProgram(program);buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,-1,1,1,-1,1,1]),gl.STATIC_DRAW);const p=gl.getAttribLocation(program,'p');gl.enableVertexAttribArray(p);gl.vertexAttribPointer(p,2,gl.FLOAT,false,0,0);texture=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,texture);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);const img=new Image();img.onload=()=>{if(closed)return;gl.bindTexture(gl.TEXTURE_2D,texture);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGB,gl.RGB,gl.UNSIGNED_BYTE,img);canvas.dataset.ready='true';draw()};img.onerror=()=>fail('The panorama image could not be loaded.');img.src=asset.url}catch(e){fail(e.message)}
 function draw(){if(closed||!gl||!program||canvas.dataset.ready!=='true')return;const ratio=Math.min(devicePixelRatio||1,2),w=Math.round(canvas.clientWidth*ratio),h=Math.round(canvas.clientHeight*ratio);if(!w||!h)return;if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}gl.viewport(0,0,w,h);for(const [name,val]of Object.entries({aspect:w/h,yaw,pitch,fov:fov*Math.PI/180}))gl.uniform1f(gl.getUniformLocation(program,name),val);gl.drawArrays(gl.TRIANGLES,0,6)}
 canvas.onpointerdown=e=>{drag={x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId);canvas.focus()};canvas.onpointermove=e=>{if(!drag)return;yaw-=(e.clientX-drag.x)*.005;pitch=Math.max(-1.45,Math.min(1.45,pitch+(e.clientY-drag.y)*.005));drag={x:e.clientX,y:e.clientY};draw()};canvas.onpointerup=()=>drag=null;canvas.onpointercancel=()=>drag=null;canvas.addEventListener('wheel',e=>{e.preventDefault();fov=Math.max(35,Math.min(100,fov+e.deltaY*.035));draw()},{passive:false});canvas.focus();
}
