import {model,entity} from './store.js';
import {esc,field,button,picture,instruction,empty,arr,select,asset} from './ui.js';
const kinds=['character','location','prop','style','panorama'];
export function renderReferences(){const all=arr(model.draft.entities),selected=entity(),list=all.filter(e=>(model.referenceKind==='all'||e.kind===model.referenceKind)&&`${e.name} ${e.description}`.toLowerCase().includes(model.query.toLowerCase()));
 return `<div class="toolbar"><div class="tabs">${['all',...kinds].map(k=>`<button data-action="reference-filter" data-id="${k}" aria-pressed="${model.referenceKind===k}">${k==='all'?'Everything':k[0].toUpperCase()+k.slice(1)}</button>`).join('')}</div><div class="row"><input class="search-input" id="reference-search" aria-label="Search references" placeholder="Find a character, place, or prop…" value="${esc(model.query)}">${button('+ Reference','new-reference','','primary')}</div></div>${selected?renderEntity(selected):''}<div class="grid">${list.map(e=>`<article class="reference-card">${picture(model.server,e.referenceIds?.[0],e.name,'card-image')}<div class="card-body"><span class="tag">${esc(e.kind)}</span><h3>${esc(e.name)}</h3><p>${esc(e.description||e.identity||'Add a reference image and the details that should stay consistent.')}</p></div><div class="card-footer"><small>${arr(e.referenceIds).length} images · ${esc(e.reviewStatus||'draft')}</small>${button('Edit reference','edit-reference',e.id,'small')}</div></article>`).join('')}</div>${!list.length?empty('Build the cast and their world','References give every scene a consistent identity, scale, and place.'):''}${instruction('References')}`;
}
function renderEntity(e){const i=model.draft.entities.findIndex(x=>x.id===e.id),base=`entities.${i}`;
 return `<section class="panel" style="margin-bottom:24px"><div class="panel-header"><div><span class="eyebrow">REFERENCE EDITOR</span><h2>${esc(e.name||'New reference')}</h2></div>${button('Done','close-reference','','quiet')}</div><div class="split"><div><div class="fields">${field('Name',base+'.name',e.name)}${select('Reference type',base+'.kind',e.kind,kinds.map(k=>({id:k,name:k[0].toUpperCase()+k.slice(1)})))}${field('Description',base+'.description',e.description,{area:true,wide:true})}${field('Identity · what makes this unmistakably them?',base+'.identity',e.identity,{area:true,wide:true,placeholder:'Face, silhouette, materials, clothing, colors…'})}${field('Scale · compare with known characters',base+'.scale',e.scale,{area:true,placeholder:'For example: Scooby’s back is broad enough for Papa and PinPin.'})}${field('Layout and geometry',base+'.geometry',e.geometry,{area:true,placeholder:'Doors, windows, routes, dimensions and things that must not move.'})}</div><details><summary>Stable identity and reference status</summary>${field('Stable ID',base+'.id',e.id,{readonly:true})}${select('Editorial status',base+'.reviewStatus',e.reviewStatus||'draft',[{id:'draft',name:'Draft'},{id:'reviewed',name:'Reviewed'},{id:'approved',name:'Approved reference'}])}<p>Reference status is descriptive. Image candidate approval is recorded separately in Production.</p></details></div><div><div class="image-strip">${arr(e.referenceIds).map(id=>{const a=asset(model.server,id);return `<div><a href="${esc(a?.url||'#')}" target="_blank" rel="noopener">${picture(model.server,id,e.name)}</a><small>${esc(a?.name||id)}</small>${e.kind==='panorama'?button('Look around 360°','panorama',id,'small'):''}${button('Detach','detach-reference',e.id+'|'+id,'small quiet')}</div>`}).join('')}</div><form data-form="upload-reference" class="upload-zone"><input type="hidden" name="entityId" value="${esc(e.id)}"><label class="field"><span>Add an image reference</span><input type="file" name="file" accept="image/png,image/jpeg,image/webp" required class="file-input"></label><button class="small">Upload & attach</button><p><small>Original bytes are preserved on the Mini. PNG, JPEG or WebP.</small></p></form><details><summary>Attach an existing project image</summary><form data-form="attach-reference"><input type="hidden" name="entityId" value="${esc(e.id)}"><label class="field"><span>Registered image</span><select name="assetId" required><option value="">Choose an image…</option>${arr(model.server.assets).map(a=>`<option value="${esc(a.id)}">${esc(a.name)}</option>`).join('')}</select></label><button class="small">Attach reference</button></form></details></div></div></section>`;
}
