import {studio,esc,title,request,post,chapter,asset,caption,notify,refresh} from './conversation-state.js';
import {renderContext,compose,showMobile} from './conversation.js';
import {renderPlan,bindPlan} from './workspace-plan.js';
import {renderSpaces,renderInsights} from './media-workspace.js';
export function renderWorkspaceHeader(){const chapters=studio.state.project.chapters;document.querySelector('#workspace-header').innerHTML=`<div class="workspace-top"><label class="chapter-select"><span class="eyebrow">ON THE DRAWING TABLE</span><select id="chapter-select" aria-label="Chapter">${chapters.map(c=>`<option value="${esc(c.id)}" ${c.id===studio.chapterId?'selected':''}>${esc(title(c.title,studio.lang)||c.id)}${c.scenes?.length?' · '+c.scenes.length+' panels':''}</option>`).join('')}</select></label><select id="language-select" aria-label="Story language"><option value="ru" ${studio.lang==='ru'?'selected':''}>RU</option><option value="en" ${studio.lang==='en'?'selected':''}>EN</option><option value="es" ${studio.lang==='es'?'selected':''}>ES</option></select></div><div class="workspace-nav"><nav aria-label="Workspace view">${[['board','Board'],['read','Read'],['references','References'],['spaces','Spaces'],['insights','Insights']].map(([id,label])=>`<button data-mode="${id}" class="${studio.mode===id&&!studio.planOpen?'active':''}">${label}</button>`).join('')}</nav><button id="plan-toggle" class="plan-toggle ${studio.planOpen?'active':''}">✎ <span>Draft plan</span></button></div>`;
 document.querySelector('#chapter-select').onchange=e=>{studio.chapterId=e.target.value;localStorage.setItem('pinpin-conversation-chapter',studio.chapterId);studio.sceneIds=[];renderContext();renderWorkspaceHeader();renderWorkspace()};
 document.querySelector('#language-select').onchange=e=>{studio.lang=e.target.value;localStorage.setItem('pinpin-studio-language',studio.lang);renderWorkspaceHeader();renderWorkspace()};
 document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{studio.mode=b.dataset.mode;studio.planOpen=false;renderWorkspaceHeader();renderWorkspace()});
 document.querySelector('#plan-toggle').onclick=()=>{studio.planOpen=!studio.planOpen;renderWorkspaceHeader();renderWorkspace()};
}
export function selectContext(context){if(context.type==='scene'){studio.sceneIds=studio.sceneIds.includes(context.id)?studio.sceneIds.filter(id=>id!==context.id):[context.id];studio.entityId=null}else if(context.type==='entity'){studio.entityId=context.id;studio.sceneIds=[]}else if(context.type==='asset'&&!studio.assetIds.includes(context.id)){if(studio.assetIds.length>=12){notify('You can attach up to 12 images.');return}studio.assetIds.push(context.id)}renderContext()}
export async function renderWorkspace({preserveScroll=false}={}){const content=document.querySelector('#workspace-content'),scroll=preserveScroll?content.scrollTop:0;if(typeof studio.mediaCleanup==='function')studio.mediaCleanup();studio.mediaCleanup=null;
 if(studio.planOpen){content.innerHTML=renderPlan();bindPlan();content.scrollTop=scroll;return}
 if(studio.mode==='spaces'||studio.mode==='insights'){content.innerHTML='';const context={state:studio.state,chapter:chapter(),lang:studio.lang,request,selectContext,compose,notify,refresh};try{studio.mediaCleanup=await(studio.mode==='spaces'?renderSpaces:renderInsights)(content,context)}catch(e){content.innerHTML=empty('This view could not open',e.message)}return}
 if(studio.mode==='references'){content.innerHTML=renderReferences();bindReferences();content.scrollTop=scroll;return}
 content.innerHTML=studio.mode==='read'?renderRead():renderBoard();bindScenes();bindBoard();content.scrollTop=scroll;
}
const empty=(heading,body)=>`<div class="workspace-empty"><span class="empty-mark">✳</span><h2>${esc(heading)}</h2><p>${esc(body)}</p></div>`;
function noScenes(){const c=chapter();if(!c)return empty('A place for your next story','Create a chapter in the full editor to get started.');const cover=asset(c.coverAssetId);return `<div class="catalogue-view">${cover?`<img class="catalogue-cover" src="${esc(cover.url)}" alt="${esc(title(c.title,studio.lang))}">`:''}<h2>${esc(title(c.title,studio.lang))}</h2><p>This chapter is in the library. Its individual panels have not been imported into this workspace.</p>${c.publicURL?`<a class="reader-link" target="_blank" rel="noopener" href="${esc(c.publicURL)}">Open published chapter ↗</a>`:''}<button data-mode-inline="plan">Start a draft plan</button></div>`}
function renderBoard(){const c=chapter();if(!c?.scenes?.length)return noScenes();const selected=c.scenes.find(s=>studio.sceneIds.includes(s.id));const boards=(studio.state.storyboards||[]).filter(b=>b.chapterId===c.id),last=boards.at(-1);
 return `<div class="board-intro"><div><h2>The story, at a glance.</h2><p>${c.scenes.length} little moments · ${c.scenes.filter(s=>s.imageAssetId).length} illustrations <span class="dot-divider">·</span> Click a panel to bring it into the conversation</p></div><div class="sheet-controls"><select id="sheet-count" aria-label="Panels per PNG sheet"><option value="6">6 / sheet</option><option value="12" selected>12 / sheet</option><option value="24">24 / sheet</option></select><button id="build-sheet" title="Create a PNG contact sheet from these actual panels">Export PNG ↗</button></div></div>${last?`<div class="sheet-links"><span>Latest sheet · ${last.panelsPerPage} panels · ${esc(last.language.toUpperCase())}</span>${last.pages.map((p,i)=>`<a href="${esc(p.url||asset(p.assetId)?.url)}" target="_blank" rel="noopener">Page ${i+1} ↗</a>`).join('')}</div>`:''}${selected?renderSelection(selected):''}<div class="scene-grid">${c.scenes.map((s,i)=>sceneCard(s,i)).join('')}</div><p class="workspace-end">The end of this chapter. Or the beginning of something new.</p>`
}
function sceneCard(s,i){const a=asset(s.imageAssetId);return `<button class="scene-card ${studio.sceneIds.includes(s.id)?'selected':''}" data-scene="${esc(s.id)}" aria-label="Select panel ${i+1}" aria-pressed="${studio.sceneIds.includes(s.id)}"><div class="scene-picture">${a?`<img loading="${i<6?'eager':'lazy'}" decoding="async" src="${esc(a.url)}" alt="${esc(caption(s))}">`:`<div class="missing-art"><span>✧</span>Room for imagination</div>`}<span class="panel-number">${String(i+1).padStart(2,'0')}</span><span class="selected-check">✓</span></div><div class="scene-caption">${esc(caption(s))}</div></button>`}
function renderSelection(s){const previous=s.imageHistory?.at(-1),before=asset(typeof previous==='string'?previous:previous?.previousAssetId||previous?.assetId||previous?.imageAssetId);return `<div class="selection-detail"><div><span class="eyebrow">PANEL ${chapter().scenes.indexOf(s)+1} · IN YOUR CONVERSATION</span><p>${esc(caption(s))}</p>${before?`<details><summary>Previous illustration</summary><img class="previous-image" src="${esc(before.url)}" alt="Previously selected illustration"><small>Current illustration remains selected in the board.</small></details>`:''}</div><button id="discuss-panel" class="primary">Discuss this panel ↗</button></div>`}
function renderRead(){const c=chapter();if(!c?.scenes?.length)return noScenes();return `<div class="reading-title"><span class="eyebrow">SETTLE IN FOR A STORY</span><h2>${esc(title(c.title,studio.lang))}</h2><p>${c.scenes.length} panels · ${studio.lang.toUpperCase()}</p></div><div class="reading-pages">${c.scenes.map((s,i)=>{const a=asset(s.imageAssetId);return `<article class="reading-panel" id="read-${esc(s.id)}">${a?`<button class="reading-image" data-scene="${esc(s.id)}" aria-label="Discuss panel ${i+1}"><img loading="${i===0?'eager':'lazy'}" decoding="async" src="${esc(a.url)}" alt="${esc(caption(s))}"></button>`:'<div class="missing-art">Illustration to come</div>'}<p>${esc(caption(s))}</p><button class="reading-discuss quiet" data-read-discuss="${esc(s.id)}">${String(i+1).padStart(2,'0')} · Discuss this moment ↗</button></article>`}).join('')}</div>`}
function bindScenes(){document.querySelectorAll('[data-scene]').forEach(b=>b.onclick=()=>{selectContext({type:'scene',id:b.dataset.scene});if(studio.mode==='board')renderWorkspace({preserveScroll:true});else{notify('Panel added to the conversation.');showMobile('chat')}});document.querySelectorAll('[data-read-discuss]').forEach(b=>b.onclick=()=>{studio.sceneIds=[b.dataset.readDiscuss];studio.entityId=null;renderContext();compose('Let’s discuss this moment. ')});const discuss=document.querySelector('#discuss-panel');if(discuss)discuss.onclick=()=>compose('Let’s discuss this panel. ');document.querySelectorAll('[data-mode-inline]').forEach(b=>b.onclick=()=>{studio.planOpen=true;renderWorkspaceHeader();renderWorkspace()})}
function bindBoard(){const b=document.querySelector('#build-sheet');if(b)b.onclick=async()=>{b.disabled=true;b.textContent='Building PNG…';try{await post('/api/storyboards',{chapterId:studio.chapterId,language:studio.lang,panelsPerPage:Number(document.querySelector('#sheet-count').value)});await refresh();renderWorkspace({preserveScroll:true});notify('Storyboard sheets are ready to open.')}catch(e){notify(e.message);b.disabled=false;b.textContent='Export PNG ↗'}}}
function renderReferences(){const entities=studio.state.project.entities;return `<div class="board-intro"><div><h2>The familiar faces. The little details.</h2><p>Characters, places, and objects that make this world its own.</p></div><a class="subtle-link" href="/legacy.html" target="_blank" rel="noopener">Manage references ↗</a></div><div class="reference-filters" role="group" aria-label="Reference type">${[['all','Everything'],['character','Characters'],['location','Places'],['prop','Objects'],['style','Style']].map(([id,label])=>`<button data-filter="${id}" class="${(studio.referenceFilter||'all')===id?'active':''}">${label}</button>`).join('')}</div><div class="reference-grid">${entities.filter(e=>!studio.referenceFilter||studio.referenceFilter==='all'||e.kind===studio.referenceFilter).map(e=>{const a=asset(e.referenceIds?.[0]);return `<button class="reference-card ${studio.entityId===e.id?'selected':''}" data-entity="${esc(e.id)}">${a?`<img loading="lazy" src="${esc(a.url)}" alt="${esc(e.name)}">`:`<div class="reference-placeholder">${esc(e.name?.[0]||'✧')}</div>`}<div><span class="eyebrow">${esc(e.kind)}</span><h3>${esc(e.name)}</h3><p>${esc(e.identity||e.description||'A reference waiting to be shaped.')}</p><span class="reference-action">Bring into conversation ↗</span></div></button>`}).join('')}</div>${!entities.length?empty('Every story begins with someone','Add your first character in the full editor, or attach an image to the conversation to explore an idea.'):''}`}
function bindReferences(){document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{studio.referenceFilter=b.dataset.filter;renderWorkspace()});document.querySelectorAll('[data-entity]').forEach(b=>b.onclick=()=>{selectContext({type:'entity',id:b.dataset.entity});renderWorkspace({preserveScroll:true});const e=studio.state.project.entities.find(e=>e.id===b.dataset.entity);compose('Let’s work on '+e.name+'. ')})}
