/* Functional browser acceptance against an isolated data directory. Never mutates the real authoring seed. */
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'/Users/miguel_lemos/.npm/_npx/e41f203b7505f1fb/node_modules/playwright');
const {spawn,execFileSync}=require('node:child_process');const fs=require('node:fs');const path=require('node:path');const assert=require('node:assert/strict');
const root=path.resolve(__dirname,'../..'),shared='/Volumes/TB4/mac-mini-storage/shared';
const output=process.env.STUDIO_TEST_OUTPUT||shared+'/pinpin-studio-browser-proof-20261002';fs.mkdirSync(output,{recursive:true});
const data=fs.mkdtempSync(shared+'/pinpin-studio-ui-test-'),port=18808,url=`http://127.0.0.1:${port}`;
const python=process.env.STUDIO_PYTHON||shared+'/pinpin-bath-magic-20261002-r16-travel-direction/.venv/bin/python';
const fixture=shared+'/pinpin-bath-magic-20261002-r17/art/opening-edits/native/scene-04-v1.png';
const fixture2=shared+'/pinpin-bath-magic-20261002-r17/art/opening-edits/native/scene-05c-v1.png';
const log=fs.openSync(output+'/test-server.log','w'),server=spawn(python,[root+'/server.py','--data-dir',data,'--media-root',shared,'--port',String(port)],{stdio:['ignore',log,log]});
const proof={passed:false,checks:[],pageErrors:[],output,data};let browser;
const check=(name)=>proof.checks.push(name);
async function state(){return fetch(url+'/api/state').then(r=>r.json())}
async function waitState(fn){for(let i=0;i<100;i++){const s=await state();if(fn(s))return s;await new Promise(r=>setTimeout(r,80))}throw Error('State condition timed out')}
function cli(args){return execFileSync(python,[root+'/cli.py','--data-dir',data,'--media-root',shared,...args],{encoding:'utf8'})}
async function stage(p,name){await p.locator(`[data-action="stage"][data-id="${name}"]`).first().click()}
async function save(p){await p.locator('#save-project').click();await p.waitForFunction(()=>document.querySelector('#save-state')?.textContent.includes('Saved on the Mini'))}
(async()=>{try{
 for(let i=0;i<100;i++){try{await state();break}catch{await new Promise(r=>setTimeout(r,100))}}
 browser=await chromium.launch({channel:'chrome',headless:true});const p=await browser.newPage({viewport:{width:1440,height:1000}});p.on('pageerror',e=>proof.pageErrors.push(e.message));
 await p.goto(url+'/legacy.html');await p.getByRole('heading',{name:'Every good story starts somewhere.'}).waitFor();
 await p.locator('[data-action="new-chapter"]').first().click();await p.locator('#new-chapter-form [name=title]').fill('A morning of surprises');await p.locator('#new-chapter-form [name=synopsis]').fill('A child fetches water, plays with a friend, and discovers a new idea.');await p.locator('#new-chapter-form button').click();
 await p.getByLabel('Chapter script',{exact:true}).fill('The family has breakfast. PinPin brings one bucket, then plays with Rabbit.');
 for(const name of ['Fetch the water','Play with leaves']){await p.locator('[data-action="new-scene"]').click();await p.getByLabel('Beat title',{exact:true}).fill(name);await p.getByLabel('Read-aloud text · RU').fill(name==='Fetch the water'?'Пин-Пин взял одно ведёрко.':'Кораблик поплыл!');await p.getByLabel('What are they actually doing?').fill(name==='Fetch the water'?'PinPin lifts one empty bucket.':'Rabbit releases a leaf into the water.');}
 await p.locator('[data-action="scene-up"]').click();await save(p);let s=await state();const chapterId=s.project.chapters[0].id,sceneId=s.project.chapters[0].scenes[0].id;assert.equal(s.project.chapters[0].scenes[0].title,'Play with leaves');await p.reload();await stage(p,'chapter');assert.equal(await p.getByLabel('Chapter script',{exact:true}).inputValue(),'The family has breakfast. PinPin brings one bucket, then plays with Rabbit.');check('chapter creation, script, stable beats, reorder, save and reload');
 await stage(p,'references');
 for(const [name,kind,file]of [['PinPin test','character',fixture],['Forest test','location',fixture2],['Panorama example','panorama',fixture]]){await p.locator('[data-action="new-reference"]').click();await p.getByLabel('Name',{exact:true}).fill(name);await p.getByLabel('Reference type').selectOption(kind);await p.locator('form[data-form="upload-reference"] input[type=file]').setInputFiles(file);await p.locator('form[data-form="upload-reference"] button').click();await p.waitForFunction(()=>document.querySelector('#save-state')?.textContent.includes('Saved on the Mini'));await p.locator('[data-action="close-reference"]').click();}
 s=await state();assert.equal(s.project.entities.length,3);assert.equal(s.assets.length,2);check('named character/location/panorama cards and immutable image uploads');
 await stage(p,'chapter');await p.locator('.choice-chips input').first().check();await p.getByLabel('Location',{exact:true}).selectOption(s.project.entities.find(e=>e.kind==='location').id);await p.getByText('Character positions, actions, and eye lines',{exact:true}).click();await p.locator('[data-action="add-blocking"]').click();await p.getByLabel('Position in the scene').fill('Beside Rabbit on the dry stone.');await p.getByLabel('Looking toward',{exact:true}).fill('The floating leaf.');await save(p);check('cast chips, named location and per-character blocking');
 await stage(p,'tempo');await p.getByLabel('Activity for beat 1').selectOption('3');await save(p);assert.equal((await state()).project.chapters[0].scenes[0].tempo.activity,3);check('editable ordinal tempo persists');
 await stage(p,'storyboard');await p.locator('form[data-form="create-storyboard"] select').selectOption('6');await p.locator('form[data-form="create-storyboard"] button').click();await p.locator('.panel-hotspot').first().waitFor();assert.equal(await p.locator('.panel-hotspot').count(),2);await p.locator('.sheet-wrap img').evaluate(i=>i.decode());await p.locator('.panel-hotspot').first().click();await p.locator('form[data-form="board-feedback"] textarea').fill('Show a closer view of the leaf before it floats away.');await p.locator('form[data-form="board-feedback"] button[value="revision"]').click();await waitState(s=>s.jobs.length===1);check('real composite PNG with placeholders, clickable panel feedback and revision handoff');
 await p.screenshot({path:output+'/storyboard-desktop.png',fullPage:false});
 await stage(p,'production');await p.locator('#job-kind').selectOption('cubemap');await p.locator('[name=panoramaAssetId]').selectOption(s.project.entities.find(e=>e.kind==='panorama').referenceIds[0]);await p.locator('[name=locationAssetId]').selectOption(s.project.entities.find(e=>e.kind==='location').referenceIds[0]);await p.locator('form[data-form="generation"] textarea').fill('Create a continuous panorama of the forest, using the successful example only for projection.');await p.locator('form[data-form="generation"] button').click();s=await waitState(s=>s.jobs.length===2);assert(s.jobs[1].referenceBindings.some(r=>r.role==='seamless-panorama'));assert(s.jobs[1].referenceBindings.some(r=>r.role==='location-identity'));check('cubemap request binds two distinct visual roles and truthful queued status');
 const imageJob=s.jobs[0];cli(['claim',imageJob.id,'--agent','browser-test']);cli(['complete',imageJob.id,'--agent','browser-test','--image',fixture2,'--scene-id',sceneId,'--visual-pass']);await p.locator('[data-action="reload"]:visible').first().click();await p.getByRole('button',{name:'Approve this version'}).click();s=await waitState(s=>s.project.chapters[0].scenes[0].status==='user-approved');assert(s.project.chapters[0].scenes[0].imageHistory.length===1);check('CLI candidate handoff, before/after, user approval and selection history');
 await stage(p,'book');await p.locator('form[data-form="instruction"] textarea').fill('Propose a quieter opening with one clear cause and effect.');await p.locator('form[data-form="instruction"] button').click();s=await waitState(s=>s.jobs.length===3);const textJob=s.jobs.at(-1);fs.writeFileSync(output+'/candidate-script.txt','The family ate together. Then PinPin fetched one bucket of water.');cli(['claim',textJob.id,'--agent','browser-test']);cli(['complete',textJob.id,'--agent','browser-test','--text-file',output+'/candidate-script.txt']);await p.locator('[data-action="reload"]:visible').first().click();await stage(p,'production');p.once('dialog',d=>d.accept());await p.getByRole('button',{name:'Use in chapter script'}).click();assert.equal(await p.getByLabel('Chapter script',{exact:true}).inputValue(),'The family ate together. Then PinPin fetched one bucket of water.');await save(p);check('plain-language instruction, completed text and deliberate Use in script');
 await p.getByLabel('Chapter script',{exact:true}).fill('LOCAL UNSAVED WORDS');let before=await p.evaluate(async()=>{const {model}=await import('/store.js');return model.revision});s=await state();s.project.book.arc='Remote edit';await fetch(url+'/api/state',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({expectedRevision:s.revision,project:s.project})});await p.evaluate(async()=>{await(await import('/store.js')).poll()});await fetch(url+'/api/jobs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind:'story-plan',instruction:'Independent agent task',chapterId})});await p.evaluate(async()=>{await(await import('/store.js')).poll()});assert.equal(await p.getByLabel('Chapter script',{exact:true}).inputValue(),'LOCAL UNSAVED WORDS');assert.deepEqual(await p.evaluate(async()=>{const {model}=await import('/store.js');return[model.conflict,model.revision]}),[true,before]);await p.locator('#save-project').click();assert.equal((await state()).project.book.arc,'Remote edit');check('remote project + job-only update cannot advance conflicted revision or overwrite local draft');
 p.once('dialog',d=>d.accept());await p.locator('[data-action="reload"]:visible').first().click();await p.getByLabel('Chapter script',{exact:true}).fill('Delayed saved draft');let release;await p.route('**/api/state',async route=>{if(route.request().method()==='PUT')await new Promise(r=>release=r);await route.continue()});await p.locator('#save-project').click();await p.waitForFunction(()=>document.body.classList.contains('busy'));assert(await p.getByLabel('Chapter script',{exact:true}).isDisabled());release();await p.waitForFunction(()=>!document.body.classList.contains('busy'));await p.unroute('**/api/state');check('pending save disables editable controls, protecting typed content');
 await p.setViewportSize({width:390,height:844});for(const st of ['book','references','chapter','tempo','storyboard','production']){await stage(p,st);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'horizontal overflow '+st)}await p.screenshot({path:output+'/production-mobile.png'});check('all six stages fit390px mobile without horizontal overflow');
 assert.equal(proof.pageErrors.length,0);proof.passed=true;
 }catch(e){proof.error=e.stack;if(browser){const pg=browser.contexts()[0]?.pages()[0];if(pg){await pg.screenshot({path:output+'/failure.png'});proof.body=await pg.locator('body').innerText();proof.model=await pg.evaluate(async()=>{const {model}=await import('/store.js');return {stage:model.stage,chapterId:model.chapterId,chapterCount:model.draft?.chapters?.length,busy:model.busy}})}}process.exitCode=1}finally{if(browser)await browser.close();server.kill('SIGTERM');fs.closeSync(log);fs.writeFileSync(output+'/browser-proof.json',JSON.stringify(proof,null,2));console.log(JSON.stringify(proof,null,2))}})();
