/* Isolated browser acceptance. Real state/uploads/boards/plan APIs; conversation transport is stubbed to avoid launching a paid agent. */
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'/Users/miguel_lemos/.npm/_npx/e41f203b7505f1fb/node_modules/playwright');
const {spawn}=require('node:child_process'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const shared='/Volumes/TB4/mac-mini-storage/shared',root=path.resolve(__dirname,'../..'),output=process.env.STUDIO_TEST_OUTPUT||shared+'/pinpin-studio-conversation-20261002',data=fs.mkdtempSync(shared+'/pinpin-conversation-ui-test-'),port=18818,url='http://127.0.0.1:'+port;
fs.mkdirSync(output,{recursive:true});
const python=process.env.STUDIO_PYTHON||shared+'/pinpin-studio-venv/bin/python',log=fs.openSync(output+'/ui-test-server.log','w'),server=spawn(python,[root+'/server.py','--data-dir',data,'--media-root',shared,'--port',String(port),'--workspace-source',root+'/web/workspace-dev','--runtime-dir',data+'-runtime'],{stdio:['ignore',log,log]});
const proof={passed:false,checks:[],pageErrors:[],data,conversationTransport:'stubbed; no model execution'},check=s=>proof.checks.push(s);let browser;
async function api(route,body,method='POST'){const r=await fetch(url+route,body===undefined?{}:{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),j=await r.json();if(!r.ok)throw Error(JSON.stringify(j));return j}
(async()=>{try{
 for(let n=0;n<100;n++){try{await api('/api/state');break}catch{await new Promise(r=>setTimeout(r,100))}}
 const live=await fetch('http://127.0.0.1:18836/api/state').then(r=>r.json()),source=live.assets.find(a=>a.mime==='image/png'),bytes=await fetch('http://127.0.0.1:18836'+source.url).then(r=>r.arrayBuffer());
 const upload=await fetch(url+'/api/assets',{method:'POST',headers:{'Content-Type':'image/png','X-File-Name':'test-reference.png'},body:bytes}).then(r=>r.json());let state=await api('/api/state');
 const scene=n=>({id:'scene-'+n,title:'Moment '+n,captions:{en:'A small moment '+n,ru:'Маленький момент '+n,es:'Un momento '+n},action:'Discover the water',dependsOn:[],castIds:['pinpin'],locationId:null,propIds:[],camera:{},tempo:{activity:1,comedy:2,discovery:3},imageAssetId:upload.asset.id,status:'draft'});
 state.project.chapters=[{id:'chapter-test',title:{en:'A little adventure',ru:'Маленькое приключение'},script:'An opening plan.',synopsis:'One quiet discovery.',scenes:[scene(1),scene(2)],coverAssetId:null}];state.project.activeChapterId='chapter-test';state.project.entities=[{id:'pinpin',kind:'character',name:'PinPin',identity:'A curious little hedgehog',referenceIds:[upload.asset.id]}];await api('/api/state',{expectedRevision:state.revision,project:state.project},'PUT');
 browser=await chromium.launch({channel:'chrome',headless:true});const p=await browser.newPage({viewport:{width:1440,height:1000}});p.on('pageerror',e=>proof.pageErrors.push(e.message));const wf=p.frameLocator('iframe.workspace-frame:not(.frame-candidate)');let conversation={id:'test',status:'idle',messages:[],plan:[],error:null},sent=0,lastSend;
 await p.route('**/api/conversation**',async route=>{const req=route.request();if(req.method()==='POST'&&req.url().endsWith('/messages')){sent++;lastSend=req.postDataJSON();conversation={...conversation,status:'running',messages:[...conversation.messages,{id:'message-'+sent,role:'user',text:lastSend.text,status:'sent',context:lastSend}]}}if(req.url().endsWith('/interrupt'))conversation.status='interrupted';await route.fulfill({contentType:'application/json',body:JSON.stringify({conversation,events:[],cursor:1})})});
 await p.goto(url);await wf.locator('.scene-card').first().waitFor();assert.equal(await wf.locator('.scene-card').count(),2);await wf.locator('.scene-card img[src^="blob:"]').first().waitFor();await wf.locator('.scene-card img[src^="blob:"]').first().evaluate(i=>i.decode());check('real registered selected images and scene captions render');
 await wf.locator('.scene-card').first().click();assert.equal(await p.locator('.context-chip').count(),1);await p.locator('#message-input').fill('Keep these half typed words');await p.locator('#message-input').focus();await p.waitForTimeout(6800);assert.equal(await p.locator('#message-input').inputValue(),'Keep these half typed words');assert.equal(await p.locator('#message-input').evaluate(e=>document.activeElement===e),true);check('polling preserves composer draft and keyboard focus');
 await p.locator('#send').click();assert.equal(sent,1);assert.equal(lastSend.sceneIds[0],'scene-1');await p.locator('#message-input').fill('Next draft while agent works');assert.equal(await p.locator('#send').isDisabled(),true);await p.locator('#interrupt').click();await p.waitForFunction(()=>!document.querySelector('#interrupt')||document.querySelector('#interrupt').classList.contains('hidden'));check('panel context submission, active turn duplicate prevention, interruption');
 await p.reload();await p.locator('.message.user').waitFor();assert.equal(await p.locator('#message-input').inputValue(),'Next draft while agent works');assert.equal(await p.locator('.message.user').count(),1);check('history snapshot and local draft restored without duplicate messages');
 await p.locator('#attachment').setInputFiles({name:'attached.png',mimeType:'image/png',buffer:Buffer.from(bytes)});await p.waitForFunction(()=>[...document.querySelectorAll('.context-chip')].some(c=>c.textContent.includes('test-reference')||c.textContent.includes('attached')));check('real image upload attaches registered asset');
 await wf.locator('[data-mode="references"]').click();await wf.locator('[data-entity="pinpin"]').click();assert.match(await p.locator('#context-strip').innerText(),/PinPin/);check('reference selection becomes conversation context');
 await wf.locator('#plan-toggle').click();await wf.locator('#plan-script').fill('A saved working plan.');await wf.locator('#save-plan').click();await wf.locator('#plan-status').filter({hasText:'awaiting'}).waitFor();assert.equal((await api('/api/state')).project.chapters[0].script,'A saved working plan.');await wf.locator('#approve-plan').click();await wf.locator('#plan-status').filter({hasText:'approved.'}).waitFor();assert.equal((await api('/api/plan?chapterId=chapter-test')).approved,true);check('revision-safe draft save and backend hashed preproduction approval');
 await wf.locator('#plan-script').fill('Unapproved next version');assert.equal(await wf.locator('#plan-status').innerText(),'Unsaved draft');await wf.locator('[data-mode="board"]').click();await wf.locator('#plan-toggle').click();assert.equal(await wf.locator('#plan-script').inputValue(),'Unapproved next version');check('unsaved script survives view changes and never shows approved');
 await wf.locator('[data-mode="board"]').click();await wf.locator('#sheet-count').selectOption('6');await wf.locator('#build-sheet').click();await wf.locator('.sheet-links a').waitFor();const board=(await api('/api/state')).storyboards.at(-1);assert.equal(board.panelsPerPage,6);assert.equal(board.pages[0].panels.length,2);check('real immutable PNG storyboard exported from selected assets');
 await p.setViewportSize({width:390,height:844});await p.locator('button[data-mobile="story"]').click();for(const mode of ['board','read','references','spaces','insights']){await wf.locator('[data-mode="'+mode+'"]').click();await p.waitForTimeout(250);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'overflow '+mode)}await p.locator('[data-mobile="chat"]').click();assert.equal(await p.locator('#message-input').isVisible(),true);check('five workspace modes and chat/story switching fit mobile');
 await p.screenshot({path:output+'/ui-test-mobile-chat.png'});assert.equal(proof.pageErrors.length,0);proof.passed=true;
 }catch(e){proof.error=e.stack;if(browser){const p=browser.contexts()[0]?.pages()[0];if(p){await p.screenshot({path:output+'/ui-test-failure.png'});proof.body=await p.locator('body').innerText()}}process.exitCode=1}finally{if(browser)await browser.close();server.kill('SIGTERM');fs.closeSync(log);fs.writeFileSync(output+'/ui-browser-proof.json',JSON.stringify(proof,null,2));console.log(JSON.stringify(proof,null,2))}})();
