/* Full app hot-reload acceptance. All conversation HTTP is stubbed; never starts a paid model. */
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'/Users/miguel_lemos/.npm/_npx/e41f203b7505f1fb/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{spawn}=require('node:child_process');
const shared='/Volumes/TB4/mac-mini-storage/shared',root=path.resolve(__dirname,'../..'),output=shared+'/pinpin-studio-kernel-20261003',tmp=fs.mkdtempSync(shared+'/pinpin-kernel-test-'),source=tmp+'/workspace-dev',runtime=tmp+'/runtime',data=tmp+'/data',url='http://127.0.0.1:18818';
fs.mkdirSync(output,{recursive:true});fs.cpSync(root+'/web/workspace-dev',source,{recursive:true});const log=fs.openSync(output+'/kernel-test-server.log','w'),server=spawn(shared+'/pinpin-studio-venv/bin/python',[root+'/server.py','--data-dir',data,'--media-root',shared,'--workspace-source',source,'--runtime-dir',runtime,'--port','18818'],{stdio:['ignore',log,log]});
const proof={passed:false,checks:[],pageErrors:[],tmp,conversationTransport:'stubbed'},check=x=>proof.checks.push(x);let browser;
async function api(route,body,method='POST'){const r=await fetch(url+route,body===undefined?{}:{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),j=await r.json();if(!r.ok)throw Error(JSON.stringify(j));return j}
async function wait(fn,timeout=25000){const end=Date.now()+timeout;while(Date.now()<end){try{const result=await fn();if(result)return result}catch{}await new Promise(r=>setTimeout(r,100))}throw Error('Condition timed out')}
async function app(p){const hash=await p.locator('#workspace-host').getAttribute('data-version');return p.frames().find(f=>f.url().includes('/workspace-builds/'+hash+'/'))}
(async()=>{try{
 await wait(()=>api('/api/state'));await wait(async()=>(await api('/api/runtime')).workspace.latest);
 let state=await api('/api/state');state.project.chapters=[{id:'chapter-test',title:{en:'A small adventure'},script:'The saved plan.',synopsis:'A quiet beginning.',scenes:[{id:'scene-one',title:'One',captions:{en:'A quiet morning'},action:'Look at the water',dependsOn:[],castIds:[],propIds:[],camera:{},tempo:{activity:1,comedy:1,discovery:1},imageAssetId:null,status:'draft'}]}];state.project.activeChapterId='chapter-test';await api('/api/state',{expectedRevision:state.revision,project:state.project},'PUT');
 browser=await chromium.launch({channel:'chrome',headless:process.env.STUDIO_HEADLESS==='1'});const context=await browser.newContext({viewport:{width:1440,height:1000}});let sends=0,lastSend,offline=false,conversation={id:'test',status:'idle',messages:[{id:'history',role:'assistant',status:'completed',text:'Existing conversation history.\n'+Array.from({length:45},(_,i)=>'Retained conversation line '+i).join('\n')}],plan:[],error:null};
 await context.route('**/api/conversation**',async route=>{const r=route.request();if(offline&&r.method()==='GET'){await route.abort('failed');return}if(r.method()==='POST'&&r.url().endsWith('/messages')){sends++;lastSend=r.postDataJSON();conversation.status='running';conversation.messages.push({id:'user-'+sends,role:'user',status:'sent',text:lastSend.text,context:lastSend},{id:'agent-'+sends,role:'assistant',status:'streaming',text:'Streaming response begins.'})}if(r.url().endsWith('/interrupt'))conversation.status='interrupted';await route.fulfill({contentType:'application/json',body:JSON.stringify({conversation,events:[],cursor:sends})})});
 const p=await context.newPage();p.on('pageerror',e=>proof.pageErrors.push(e.message));await p.goto(url+'/?chapter=chapter-test&lang=en&view=board&ui=live');await p.waitForFunction(()=>document.querySelector('#workspace-host')?.dataset.version?.length===64);let f=await app(p);await f.locator('#message-input').waitFor();assert.equal(await p.locator('#message-input').count(),0);assert.equal(await p.locator('#kernel-fallback').isHidden(),true);check('normal conversation, composer and workspace all live in one editable app frame');offline=true;await f.locator('#connection.offline').waitFor();offline=false;await f.locator('#connection:not(.offline)').waitFor();check('conversation transport recovers visibly from offline to online');
 assert.equal(await f.evaluate(()=>{try{return !!parent.document.body}catch{return false}}),false);assert.equal(await f.evaluate(()=>{try{localStorage.setItem('x','y');return true}catch{return false}}),false);check('opaque app cannot read parent DOM or storage');
 await f.locator('.scene-card').click();await f.locator('#message-input').fill('Current keyboard behavior');await f.locator('#message-input').press('Enter');assert.equal(await f.locator('#message-input').inputValue(),'Current keyboard behavior\n');assert.equal(sends,0);check('existing ordinary Enter newline behavior remains unchanged');
 await f.locator('#message-input').fill('A normal send through the typed bridge');await f.locator('#send').click();await wait(()=>sends===1);assert.equal(lastSend.sceneIds[0],'scene-one');await f.locator('#message-input').fill('Unsent draft stays with me');await f.locator('#message-input').evaluate(e=>e.setSelectionRange(7,12));await f.locator('#message-input').press('ArrowLeft');await f.locator('#messages').evaluate(e=>e.scrollTo({top:120,behavior:'instant'}));await wait(()=>p.evaluate(()=>Number(sessionStorage.getItem('pinpin-conversation-scroll'))>=100));const oldHash=await p.locator('#workspace-host').getAttribute('data-version');await p.evaluate(()=>window.__kernelNode=document.querySelector('.kernel-shell'));const seqBefore=await p.evaluate(()=>Number(sessionStorage.getItem('pinpin-conversation-draft-seq')));
 const layout=fs.readFileSync(source+'/chat-layout.js','utf8');fs.writeFileSync(source+'/chat-layout.js',layout.replace('What shall we make happen next?','Editable chat proof'));
 conversation.messages.at(-1).text='Streaming response continued while the whole app changed.';
 await wait(async()=>{const h=await p.locator('#workspace-host').getAttribute('data-version');return h&&h!==oldHash});f=await app(p);await f.locator('#message-input').waitFor();assert.equal(await f.locator('#message-input').getAttribute('placeholder'),'Editable chat proof');assert.equal(await f.locator('#message-input').inputValue(),'Unsent draft stays with me');assert.equal(await p.evaluate(()=>window.__kernelNode===document.querySelector('.kernel-shell')),true);await wait(async()=>(await f.locator('#messages').innerText()).includes('continued while'));assert.match(await f.locator('#context-strip').innerText(),/Panel 1/);assert.equal(await f.locator('#send').isDisabled(),true);assert((await f.locator('#messages').evaluate(e=>e.scrollTop))>=100);check('editing chat source hot-replaces the full app while kernel, streaming transcript, draft, scroll and selection survive');
 await f.locator('#message-input').evaluate(e=>{e.focus();e.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',metaKey:true,bubbles:true,cancelable:true}))});await p.waitForTimeout(100);assert.equal(sends,1);check('parent in-flight guard prevents a new app from duplicating an active turn');
 const child=fs.readFileSync(source+'/child.js','utf8');fs.writeFileSync(source+'/child.js',child+"\nimport {command as candidateCommand} from './bridge.js';candidateCommand('send',{text:'FORBIDDEN candidate send'}).then(()=>window.__candidateAccepted=true).catch(e=>window.__candidateDenied=e.message);\n");
 const beforeCandidate=await p.locator('#workspace-host').getAttribute('data-version');await wait(async()=>(await p.locator('#workspace-host').getAttribute('data-version'))!==beforeCandidate);f=await app(p);await wait(()=>f.evaluate(()=>window.__candidateDenied));assert.match(await f.evaluate(()=>window.__candidateDenied),/active app/);assert.equal(sends,1);check('a candidate frame cannot send before activation');
 const goodHash=await p.locator('#workspace-host').getAttribute('data-version');fs.writeFileSync(source+'/child.js',child+'\nfunction broken( {');await wait(async()=>(await api('/api/runtime')).workspace.status==='error');assert.equal(await p.locator('#workspace-host').getAttribute('data-version'),goodHash);check('invalid JavaScript preserves the last working full app');
 fs.writeFileSync(source+'/child.js',child.replace("if(value.type==='init'){","if(value.type==='init'){throw Error('App render failed for recovery test');"));await wait(async()=>(await api('/api/runtime')).workspace.latest!==goodHash);await p.waitForFunction(()=>document.querySelector('#preview-error')?.textContent.includes('App render failed'));assert.equal(await p.locator('#workspace-host').getAttribute('data-version'),goodHash);check('a render-failing candidate leaves the current chat UI alive');
 await p.reload();await p.locator('#fallback-input').waitFor({state:'visible'});await p.waitForFunction(()=>document.querySelector('#preview-error')?.textContent.includes('App render failed'));assert.equal(await p.locator('#fallback-input').inputValue(),'Unsent draft stays with me');assert.match(await p.locator('#fallback-messages').innerText(),/A normal send/);await p.locator('#fallback-stop').click();await wait(()=>conversation.status==='interrupted');await p.locator('#fallback-input').fill('Recovery chat still sends');await p.locator('#fallback-send').click();await wait(()=>sends===2);assert.equal(lastSend.sceneIds[0],'scene-one');await p.locator('#fallback-stop').click();check('after a broken-build reload, minimal recovery chat restores draft/history/context and can send and interrupt');
 fs.writeFileSync(source+'/child.js',child);await wait(async()=>(await api('/api/runtime')).workspace.status==='ready');await p.locator('#recover-workspace').click();await p.waitForFunction(()=>document.querySelector('#workspace-host')?.dataset.version?.length===64);await p.locator('#communication-toggle').click();await p.locator('#fallback-input').waitFor({state:'visible'});await p.locator('#fallback-close').click();f=await app(p);await f.locator('#message-input').waitFor();check('recovery conversation remains manually accessible after app restoration');
 const rev=(await api('/api/state')).revision,review=await context.newPage();await review.goto(url+'/?chapter=chapter-test&view=board&lang=en&ui='+(await p.locator('#workspace-host').getAttribute('data-version'))+'&rev='+rev);await review.waitForFunction(()=>document.querySelector('#workspace-host')?.dataset.version?.length===64);const rf=await app(review);await rf.locator('#message-input').fill('Discuss this saved review');await rf.locator('#send').click();await wait(()=>sends===3);assert.equal(lastSend.projectRevision,rev);assert.equal(lastSend.chapterId,'chapter-test');check('typed chat send uses the parent-authoritative pinned project revision and selected chapter');const uploadDenied=await rf.evaluate(async()=>{const{command}=await import('./bridge.js');try{await command('upload',{buffer:new ArrayBuffer(8),mime:'image/png',name:'review.png'});return false}catch(e){return e.message}});assert.match(uploadDenied,/read-only/);check('parent rejects typed image upload from a pinned review');
 await review.close();await p.setViewportSize({width:390,height:844});f=await app(p);await f.locator('button[data-mobile="chat"]').click();assert.equal(await f.locator('#message-input').isVisible(),true);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.equal(await f.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await p.screenshot({path:output+'/kernel-mobile.png'});check('full app and recovery kernel fit mobile');
 assert.equal(proof.pageErrors.length,0);proof.passed=true;
 }catch(e){proof.error=e.stack;if(browser){const p=browser.contexts()[0]?.pages()[0];if(p){await p.screenshot({path:output+'/kernel-failure.png'});proof.body=await p.locator('body').innerText()}}process.exitCode=1}finally{if(browser)await browser.close();server.kill('SIGTERM');fs.closeSync(log);fs.writeFileSync(output+'/kernel-browser-proof.json',JSON.stringify(proof,null,2));console.log(JSON.stringify(proof,null,2))}})();
