import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
// Load exact browser modules without requiring package.json/type changes in the repo.
const cache=new Map();function load(filename){filename=path.resolve(filename);if(cache.has(filename))return cache.get(filename);let text=fs.readFileSync(filename,'utf8');text=text.replace(/from ['"](\.[^'"]+)['"]/g,(_,relative)=>'from '+JSON.stringify(load(path.resolve(path.dirname(filename),relative.split('?')[0]))));const url='data:text/javascript;base64,'+Buffer.from(text).toString('base64');cache.set(filename,url);return url;}
const here=path.dirname(fileURLToPath(import.meta.url));
const {loop,nearestAvailable,buildLocationDescriptor}=await import(load(path.join(here,'../workspace-dev/location-viewer.js')));
const {tourGestures}=await import(load(path.join(here,'../workspace-dev/location-viewer-support/tractor-viewer-gestures.js')));
const {locationViewerRequest}=await import(load(path.join(here,'../workspace-dev/media-workspace.js')));
const {installCapabilities,businessRequest}=await import(load(path.join(here,'../business-extension-contract.js')));
let checks=0;function ok(value){assert.ok(value);checks++;}function throws(fn){assert.throws(fn);checks++;}
const registry=JSON.parse(fs.readFileSync(new URL('../../../../workflows/examples/location-viewer/media-registry.json',import.meta.url))).files;
const manifest=JSON.parse(fs.readFileSync(new URL('../../../../workflows/examples/location-viewer/location-manifest.json',import.meta.url)));
const metadata={schemaVersion:1,protocol:'pinpin-business-json-v1',businessHash:'a'.repeat(64),operations:[{id:'spaces.location.get.v1',effect:'read',method:'POST',request:{type:'object',fields:{mediaId:{type:'id',maxLength:160}},required:['mediaId']},maxRequestBytes:32768,maxResponseBytes:65536,timeoutMs:10000}]};const installed=installCapabilities(metadata,metadata.businessHash);ok(businessRequest('/api/business/spaces.location.get.v1',locationViewerRequest('tractor-orbit-scrub-v1'),true,false,installed).options.method==='POST');throws(()=>businessRequest('/api/business/spaces.location.get.v1',{...locationViewerRequest('tractor-orbit-scrub-v1'),headers:{'Content-Type':'application/json'}},true,false,installed));
const d=buildLocationDescriptor(manifest,registry);ok(d.stops.length===1);ok(d.stops[0].actualTimestampSeconds===5.625);ok(d.stops[0].sourceLockStatus==='experimental');ok(d.stops[0].camera.fov===63.108676232412364);ok(d.orbit.mime==='video/mp4');ok(d.stops[0].available);ok(loop(-.2)>.799&&loop(1.2)<.201);
throws(()=>buildLocationDescriptor({...manifest,stops:[{...manifest.stops[0],actualTimestampSeconds:undefined}]},registry));throws(()=>buildLocationDescriptor({...manifest,orbit:{id:d.orbit.id,sha256:'a'.repeat(64)}},registry));throws(()=>buildLocationDescriptor({...manifest,stops:[{...manifest.stops[0],camera:{yaw:0,pitch:0,fov:Infinity}}]},registry));
const stops=[{id:'unavailable',available:false,actualTimestampSeconds:0},{id:'last',available:true,actualTimestampSeconds:9.5},{id:'middle',available:true,actualTimestampSeconds:5}];ok(nearestAvailable(stops,.01,10).id==='last');ok(nearestAvailable(stops,.49,10).id==='middle');ok(nearestAvailable([],0,10)===null);ok(nearestAvailable(stops,0,NaN)===null);
class Target{constructor(){this.listeners=new Map();this.dataset={};this.clientWidth=300;this.clientHeight=200;this.captures=new Set();}addEventListener(n,fn){const a=this.listeners.get(n)||[];a.push(fn);this.listeners.set(n,a);}removeEventListener(n,fn){this.listeners.set(n,(this.listeners.get(n)||[]).filter(x=>x!==fn));}fire(n,e={}){e.target??={closest:()=>false};e.preventDefault??=()=>{};for(const fn of this.listeners.get(n)||[])fn(e);}setPointerCapture(id){this.captures.add(id);}hasPointerCapture(id){return this.captures.has(id);}releasePointerCapture(id){this.captures.delete(id);}count(){return [...this.listeners.values()].reduce((n,a)=>n+a.length,0);}}
globalThis.document=new Target();globalThis.matchMedia=()=>({matches:false});let frame=0;const frames=new Map();globalThis.requestAnimationFrame=fn=>{frames.set(++frame,fn);return frame;};globalThis.cancelAnimationFrame=id=>frames.delete(id);function flush(){const work=[...frames.values()];frames.clear();work.forEach(fn=>fn());}
const stage=new Target();let looks=0,orbits=[],drag=0,zoom=0;const g=tourGestures(stage,{progress:()=>.95,startLook:()=>looks++,drag:x=>drag+=x,orbit:p=>orbits.push(p),zoom:z=>zoom+=z,wheelInput:(x,y,p)=>orbits.push(p?'pinch':'scroll'),isLooking:()=>true,cancelInput:()=>{}});
const touch=(id,x,y)=>({pointerId:id,clientX:x,clientY:y,pointerType:'touch',buttons:1,button:0});
stage.fire('pointerdown',touch(1,10,10));stage.fire('pointermove',touch(1,30,10));ok(looks===1&&drag===20);stage.fire('pointerup',touch(1,30,10));stage.fire('pointerdown',touch(1,5,10));stage.fire('pointermove',touch(1,25,10));ok(looks===2&&drag===40);stage.fire('pointerup',touch(1,25,10));
stage.fire('pointerdown',touch(1,10,10));stage.fire('pointerdown',touch(2,60,10));stage.fire('pointermove',touch(1,40,10));stage.fire('pointermove',touch(2,90,10));flush();ok(orbits.length===1&&orbits[0]>1);stage.fire('pointerup',touch(1,40,10));stage.fire('pointerup',touch(2,90,10));
stage.fire('pointerdown',touch(1,10,10));stage.fire('pointerdown',touch(2,60,10));stage.fire('pointermove',touch(1,5,10));stage.fire('pointermove',touch(2,65,10));flush();ok(zoom!==0);stage.fire('pointercancel',touch(1,5,10));stage.fire('pointercancel',touch(2,65,10));
ok(stage.count()>0&&document.count()>0);g.destroy();ok(stage.count()===0&&document.count()===0&&stage.captures.size===0&&frames.size===0);
console.log(JSON.stringify({checks,passed:true,kind:'descriptor and exact-derived gesture tests; browser decode not claimed'}));
