/* Runtime integration: actual immutable builds + project APIs, no paid conversation turn. */
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'/Users/miguel_lemos/.npm/_npx/e41f203b7505f1fb/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{spawn}=require('node:child_process');
const shared='/Volumes/TB4/mac-mini-storage/shared',root=path.resolve(__dirname,'../..'),output=shared+'/pinpin-studio-shell-20261003',tmp=fs.mkdtempSync(shared+'/pinpin-shell-test-'),source=tmp+'/workspace-dev',runtime=tmp+'/runtime',data=tmp+'/data',url='http://127.0.0.1:18818';
fs.mkdirSync(output,{recursive:true});fs.cpSync(root+'/web/workspace-dev',source,{recursive:true});
const log=fs.openSync(output+'/shell-test-server.log','w'),python=shared+'/pinpin-studio-venv/bin/python',server=spawn(python,[root+'/server.py','--data-dir',data,'--media-root',shared,'--workspace-source',source,'--runtime-dir',runtime,'--port','18818'],{stdio:['ignore',log,log]});
let browser;const proof={passed:false,checks:[],pageErrors:[],tmp};const check=s=>proof.checks.push(s);
async function api(route,body,method='POST'){const r=await fetch(url+route,body===undefined?{}:{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw Error(JSON.stringify(j));return j}
async function waitFor(fn,timeout=20000){const end=Date.now()+timeout;while(Date.now()<end){try{const x=await fn();if(x)return x}catch{}await new Promise(r=>setTimeout(r,150))}throw Error('Condition timed out')}
async function currentFrame(p){return p.frames().find(f=>f.url().includes('/workspace-builds/')&&!f.isDetached()&&f.url().includes(awaitHash));}
let awaitHash='';
(async()=>{try{
 await waitFor(()=>api('/api/state'));await waitFor(async()=>!!(await api('/api/runtime')).workspace.latest);
 const live=await fetch('http://127.0.0.1:18836/api/state').then(r=>r.json()),image=live.assets.find(a=>a.mime==='image/png'),raw=await fetch('http://127.0.0.1:18836'+image.url).then(r=>r.arrayBuffer()),uploaded=await fetch(url+'/api/assets',{method:'POST',headers:{'Content-Type':'image/png','X-File-Name':'shell-fixture.png'},body:raw}).then(r=>r.json());
 let s=await api('/api/state');const scene=i=>({id:'s-'+i,title:'Moment '+i,captions:{en:'Story moment '+i,ru:'Момент '+i},action:'A quiet discovery',dependsOn:[],castIds:[],propIds:[],camera:{},tempo:{activity:1,comedy:1,discovery:1},imageAssetId:uploaded.asset.id,status:'draft'});s.project.chapters=[{id:'test-chapter',title:{en:'The original chapter',ru:'История'},script:'The saved script.',synopsis:'One small discovery',scenes:Array.from({length:30},(_,i)=>scene(i)),coverAssetId:null}];s.project.entities=[{id:'pinpin',name:'PinPin',kind:'character',referenceIds:[]}];s.project.activeChapterId='test-chapter';await api('/api/state',{expectedRevision:s.revision,project:s.project},'PUT');
 browser=await chromium.launch({channel:'chrome',headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000}}),p=await context.newPage();p.on('pageerror',e=>proof.pageErrors.push(e.message));await p.goto(url+'/?chapter=test-chapter&view=board&lang=en&ui=live');
 await p.waitForFunction(()=>document.querySelector('#workspace-host').dataset.version.length===64);let hash=await p.locator('#workspace-host').getAttribute('data-version');awaitHash=hash;let frame=await currentFrame(p);await frame.locator('.scene-card').first().waitFor();assert.equal(await frame.locator('.scene-card').count(),30);await waitFor(()=>frame.locator('.scene-card img').first().evaluate(i=>i.naturalWidth>0));assert.match(await frame.locator('.scene-card img').first().getAttribute('src'),/^blob:/);check('real immutable workspace and registered image bytes load inside opaque sandbox');
 assert.equal(await frame.evaluate(()=>{try{return !!parent.document.body}catch{return false}}),false);assert.equal(await frame.evaluate(()=>{try{localStorage.setItem('unsafe','1');return true}catch{return false}}),false);
 const denied=await frame.evaluate(async()=>{const {rpc}=await import('./bridge.js');try{await rpc('/api/conversation/messages',{method:'POST',body:JSON.stringify({text:'must not send'})});return false}catch(e){return e.message}});assert.match(denied,/not allowed|not available/);check('sandbox denies parent DOM/storage and bridge denies conversation endpoint');
 await frame.locator('.scene-card').first().click();await p.waitForURL(/scene=s-0/);await p.locator('#message-input').fill('My private half-typed draft');await p.evaluate(()=>{window.__composer=document.querySelector('#message-input');window.__shell=document.querySelector('.studio-shell')});
 await frame.locator('#plan-toggle').click();await frame.locator('#plan-script').fill('Unsaved plan across a new UI build');await waitFor(()=>p.evaluate(()=>JSON.parse(sessionStorage.getItem('pinpin-workspace-session-v1')||'{}').planDrafts?.['test-chapter']?.script==='Unsaved plan across a new UI build'));
 await p.locator('#message-input').focus();const css=fs.readFileSync(source+'/workspace.css','utf8');fs.writeFileSync(source+'/workspace.css',css+'\n/* shell runtime hot edit proof */\n');
 await waitFor(async()=>{const h=await p.locator('#workspace-host').getAttribute('data-version');return h!==hash&&h.length===64},30000);const nextHash=await p.locator('#workspace-host').getAttribute('data-version');awaitHash=nextHash;frame=await currentFrame(p);
 assert.equal(await p.locator('#message-input').inputValue(),'My private half-typed draft');assert.equal(await p.evaluate(()=>window.__composer===document.querySelector('#message-input')&&window.__shell===document.querySelector('.studio-shell')),true);assert.equal(await p.evaluate(()=>document.activeElement===window.__composer),true);assert.equal(await frame.locator('#plan-script').inputValue(),'Unsaved plan across a new UI build');assert.match(await p.locator('#context-strip').innerText(),/Panel 1/);check('actual source edit swaps frame only; chat DOM/focus/draft, selected panel and unsaved plan survive');
 const child=fs.readFileSync(source+'/child.js','utf8');fs.writeFileSync(source+'/child.js',child+'\nfunction broken( {\n');await waitFor(async()=>(await api('/api/runtime')).workspace.status==='error');await p.waitForTimeout(2100);assert.equal(await p.locator('#workspace-host').getAttribute('data-version'),nextHash);assert.equal(await p.locator('#message-input').inputValue(),'My private half-typed draft');check('invalid JavaScript build leaves last good frame and conversation alive');
 fs.writeFileSync(source+'/child.js',child.replace("await render();send('ready'","throw Error('Candidate render failure');await render();send('ready'"));await waitFor(async()=>(await api('/api/runtime')).workspace.latest!==nextHash);await p.waitForFunction(()=>document.querySelector('#preview-error').textContent.includes('Candidate render failure'),{timeout:20000});assert.equal(await p.locator('#workspace-host').getAttribute('data-version'),nextHash);check('runtime render failure rejects candidate before replacing last good workspace');
 fs.writeFileSync(source+'/child.js',child);await waitFor(async()=>(await api('/api/runtime')).workspace.status==='ready');await p.locator('#recover-workspace').click();await p.waitForTimeout(2200);
 awaitHash=await p.locator('#workspace-host').getAttribute('data-version');frame=await currentFrame(p);await frame.locator('[data-mode="references"]').click();await p.waitForURL(/view=references/);await frame.locator('[data-mode="read"]').click();await p.waitForURL(/view=read/);await p.goBack();await p.waitForURL(/view=references/);await frame.locator('.reference-card').waitFor();await p.goForward();await p.waitForURL(/view=read/);await frame.locator('.reading-title').waitFor();check('browser Back and Forward restore workspace route without reloading shell');
 await p.evaluate(()=>{Object.defineProperty(navigator,'clipboard',{value:{writeText:async text=>{window.__copied=text}},configurable:true})});await p.locator('#copy-review-link').click();const copied=await p.evaluate(()=>window.__copied);const parsed=new URL(copied);assert.match(parsed.searchParams.get('ui'),/^[a-f0-9]{64}$/);assert.match(parsed.searchParams.get('rev'),/^\d+$/);assert.equal(copied.includes('private'),false);
 const review=await context.newPage();await review.goto(copied);await review.waitForFunction(()=>document.querySelector('#workspace-host').dataset.version.length===64);const rf=review.frames().find(f=>f.url().includes('/workspace-builds/'));await rf.locator('.reading-title').waitFor();assert.match(await review.locator('#review-revision').innerText(),/Review/);
 const readOnly=await rf.evaluate(async()=>{const{rpc}=await import('./bridge.js');const s=await rpc('/api/state?revision=999999');try{await rpc('/api/state',{method:'PUT',body:JSON.stringify({expectedRevision:s.revision,project:s.project})});return false}catch(e){return {blocked:e.message,readOnly:s.readOnly,revision:s.revision}}});assert.equal(readOnly.readOnly,true);assert.equal(readOnly.revision,Number(parsed.searchParams.get('rev')));assert.match(readOnly.blocked,/read-only/);check('review link replays pinned build/view/selection/revision in new tab; parent blocks mutations and ignores live-state escape');
 const pinned=await review.locator('#workspace-host').getAttribute('data-version');fs.writeFileSync(source+'/workspace.css',css+'\n/* third live build */\n');await waitFor(async()=>(await api('/api/runtime')).workspace.latest!==pinned);await review.waitForTimeout(2400);assert.equal(await review.locator('#workspace-host').getAttribute('data-version'),pinned);check('pinned review remains on exact UI version while live preview updates');
 await p.setViewportSize({width:390,height:844});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await p.locator('button[data-mobile="chat"]').click();assert.equal(await p.locator('#message-input').isVisible(),true);await p.screenshot({path:output+'/shell-mobile-chat.png'});await p.setViewportSize({width:1440,height:1000});await p.screenshot({path:output+'/shell-desktop.png'});check('mobile Conversation/Story layout remains usable');
 proof.passed=true;
 }catch(e){proof.error=e.stack;if(browser){const p=browser.contexts()[0]?.pages()[0];if(p){await p.screenshot({path:output+'/shell-failure.png'});proof.body=await p.locator('body').innerText()}}process.exitCode=1}finally{if(browser)await browser.close();server.kill('SIGTERM');fs.closeSync(log);fs.writeFileSync(output+'/shell-browser-proof.json',JSON.stringify(proof,null,2));console.log(JSON.stringify(proof,null,2))}})();
