import {studio,esc,chapter,asset,emitUI} from './child-state.js';
import {chat,active,persistDraft,persistContext} from './chat-state.js';
import {bindComposer,synchronizeDraft,updateControls} from './chat-composer.js';
import {layout} from './chat-layout.js';
import {bindActions} from './child-actions.js';
import {renderWorkspace} from './workspace.js';
let scrollFrame=0,noticeTimer;

export function showMobile(mode){chat.mobile=mode;studio.mobile=mode;emitUI(true);const shell=document.querySelector('.studio-shell');if(!shell)return;shell.dataset.mobile=mode;document.querySelectorAll('.mobile-switch button').forEach(b=>b.classList.toggle('selected',b.dataset.mobile===mode));}
export function compose(text){const input=document.querySelector('#message-input');const current=input.value.trim();input.value=current&&current!==text.trim()?input.value+'\n\n'+text:text;persistDraft(input.value);showMobile('chat');input.focus();updateControls();}
function contextLabels(value){const labels=[];if(value?.sceneIds?.length)labels.push(value.sceneIds.length+' selected panel'+(value.sceneIds.length>1?'s':''));if(value?.entityId)labels.push(studio.state.project.entities.find(e=>e.id===value.entityId)?.name||'Reference');return labels;}
function welcome(){return `<div class="welcome"><h2>Small moments.<br>Wonderful stories.</h2><p>Shape the next chapter with your creative partner. Talk through an idea, choose a panel, or bring a character into the conversation.</p><div class="suggestions"><button class="suggestion" data-prompt="Help me plan the next chapter. Start by asking what I have in mind.">Let's shape a story <span>↗</span></button><button class="suggestion" data-prompt="Read this chapter and suggest where we could give the story more room to breathe. Propose a plan before changing anything.">Look at the rhythm <span>↗</span></button><button class="suggestion" data-prompt="Help me develop a character, keeping their existing references in mind.">Explore a character <span>↗</span></button></div></div>`;}
export function renderConversation(){
 const container=document.querySelector('#messages');if(!container)return;const messages=chat.conversation?.messages||[],key=JSON.stringify(messages);
 if(key!==chat.key||!container.children.length){const first=!container.children.length,bottom=container.scrollHeight-container.scrollTop-container.clientHeight<90,previous=container.scrollTop;chat.key=key;container.innerHTML=messages.length?messages.map(m=>`<article class="message ${m.role==='user'?'user':'assistant'}" data-message-id="${esc(m.id)}"><div class="message-label"><span>${m.role==='user'?'You':'Studio · Codex'}</span><span>${m.status==='streaming'?'Writing…':m.status==='error'?'Failed':m.status==='interrupted'?'Interrupted':''}</span></div><div class="message-text">${esc(m.text||'')}</div>${contextLabels(m.context).length||m.context?.assetIds?.length?`<div class="message-context">${contextLabels(m.context).map(t=>'<span>'+esc(t)+'</span>').join('')}${(m.context?.assetIds||[]).map(id=>{const a=asset(id);return a?`<img data-asset-src="${esc(a.url)}" alt="${esc(a.name)}">`:'';}).join('')}</div>`:''}</article>`).join(''):welcome();container.querySelectorAll('[data-prompt]').forEach(b=>b.onclick=()=>compose(b.dataset.prompt));container.scrollTo({top:first&&Number.isFinite(chat.scroll)?chat.scroll:bottom?container.scrollHeight:previous,behavior:'instant'});}
 const current=chat.conversation,status=document.querySelector('#turn-status');let progress='';if(active())progress=`<div class="activity"><span class="activity-dot"></span>${current.status==='connecting'?'Connecting to Codex…':current.status==='interrupting'?'Stopping the current turn…':'Codex is working…'}</div>`;if(Array.isArray(current?.plan)&&active())progress+=current.plan.map(p=>'<div>'+esc(p.step||p.text||p.title||'')+'</div>').join('');const error=current?.error?.message||chat.connectionError;status.innerHTML=progress+(error?'<div class="turn-error">'+esc(error)+'</div>':'');const connection=document.querySelector('#connection');connection.textContent=chat.connectionError?'Conversation unavailable':'Connected to your studio';connection.classList.toggle('offline',Boolean(chat.connectionError));synchronizeDraft();
}
export function renderContext(){const strip=document.querySelector('#context-strip');if(!strip)return;const chips=[];for(const id of studio.sceneIds){const s=chapter()?.scenes.find(s=>s.id===id);if(s)chips.push({type:'scene',id,label:'Panel '+(chapter().scenes.indexOf(s)+1),asset:asset(s.imageAssetId)});}if(studio.entityId){const e=studio.state.project.entities.find(e=>e.id===studio.entityId);if(e)chips.push({type:'entity',id:e.id,label:e.name,asset:asset(e.referenceIds?.[0])});}for(const id of studio.assetIds){const a=asset(id);if(a)chips.push({type:'asset',id,label:a.name,asset:a});}const key=JSON.stringify(chips);if(key===chat.contextKey)return;chat.contextKey=key;strip.innerHTML=chips.map(c=>`<div class="context-chip">${c.asset?`<img data-asset-src="${esc(c.asset.url)}" alt="">`:''}<span>${esc(c.label)}</span><button type="button" data-remove="${c.type}" data-id="${esc(c.id)}" aria-label="Remove ${esc(c.label)} from context">×</button></div>`).join('');strip.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{if(b.dataset.remove==='scene')studio.sceneIds=studio.sceneIds.filter(id=>id!==b.dataset.id);if(b.dataset.remove==='entity')studio.entityId=null;if(b.dataset.remove==='asset')studio.assetIds=studio.assetIds.filter(id=>id!==b.dataset.id);persistContext();emitUI();renderContext();renderWorkspace({preserveScroll:true});});}
export function renderChat(){renderConversation();renderContext();}
export function mountChat(){document.querySelector('#studio').innerHTML=layout();chat.key='';chat.contextKey='';bindComposer({render:renderChat,renderContext});bindActions({compose,showMobile,renderContext});document.querySelectorAll('.mobile-switch button').forEach(b=>b.onclick=()=>showMobile(b.dataset.mobile));document.querySelector('#messages').addEventListener('scroll',()=>{if(scrollFrame)return;scrollFrame=requestAnimationFrame(()=>{scrollFrame=0;persistDraft(document.querySelector('#message-input').value,{scroll:document.querySelector('#messages').scrollTop});});});document.addEventListener('studio-notify',event=>{const node=document.querySelector('#notification');node.textContent=event.detail;node.classList.add('visible');clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>node.classList.remove('visible'),6500);});renderChat();showMobile(studio.mobile);}
