import {renderBookPlan,bindBookPlan} from './book-plan.js';
import {rpc} from './bridge.js';
import {compose} from './child-actions.js';
import {renderChapterDraft,bindChapterDraft,rememberDraftEditors} from './chapter-draft.js';
import {studio,esc,chapter,post,request,notify,emitUI} from './child-state.js';
import {renderWorkspace,renderWorkspaceHeader} from './workspace.js';
const currentDraft=()=>{const c=chapter();if(!c)return null;if(studio.readOnly)return {script:c.script||'',baseScript:c.script||'',baseRevision:studio.state.revision};if(!studio.planDrafts.has(c.id))studio.planDrafts.set(c.id,{script:c.script||'',baseScript:c.script||'',baseRevision:studio.state.revision});return studio.planDrafts.get(c.id)};
export function renderPlan(){rememberDraftEditors();const c=chapter(),draft=currentDraft();const book='<div data-plan-revision="'+studio.state.revision+'" id="book-plan-surface">Loading saved book intent…</div><div id="location-reference-surface"></div>';if(!c)return book+'<div class="workspace-empty"><h2>Select a chapter first.</h2></div>';if(c.studioDraft)return `${book}${renderChapterDraft(c)}<div class="plan-view"><h3>Saved script</h3><p>Revise panels in conversation. Full-production authorization is separate from rough storyboard work.</p><pre style="white-space:pre-wrap">${esc(c.script||'')}</pre></div>`;const approved=false;return `${book}${renderChapterDraft(c)}<div class="plan-view"><span class="eyebrow">A WORKING DRAFT</span><h2>Give the story its shape.</h2><p class="plan-explainer">Keep a script or a plan here. Save it as you go, then approve this exact version when it feels right.</p><label for="plan-script">Chapter script &amp; plan</label><textarea id="plan-script" rows="18" placeholder="A beginning, a small discovery, a surprising turn…">${esc(draft.script)}</textarea><div class="plan-actions"><span id="plan-status">${approved?'This plan version is approved.':draft.script!==c.script?'Unsaved draft':'Draft · not yet approved'}</span><button id="save-plan">Save draft</button><button id="approve-plan" class="primary" ${!draft.script.trim()&&!c.scenes.length?'disabled':''}>Approve this plan</button></div><p class="plan-footnote">Approval records this script, scene staging, camera directions, and reference bindings. Changing the plan requires a new approval. Image review and publication remain separate.</p><div class="plan-review"><h3>The chapter in one sentence</h3><p>${esc(c.synopsis||'Use the conversation to explore the chapter’s central idea.')}</p><small>${c.scenes.length} panels in the current chapter</small></div></div>`}
export function bindPlan(){bindBookSurface();bindLocationSurface();const managed=chapter();if(managed?.studioDraft){bindChapterDraft(managed,renderWorkspace);return;}const input=document.querySelector('#plan-script');if(!input)return;if(studio.readOnly){input.readOnly=true;document.querySelectorAll('.plan-actions button').forEach(b=>b.disabled=true);document.querySelector('#plan-status').textContent='Pinned revision · switch to Live to edit';return;}input.oninput=()=>{const d=currentDraft();d.script=input.value;emitUI(true);document.querySelector('#plan-status').textContent=d.script===(chapter().script||'')?'Saved draft':'Unsaved draft';document.querySelector('#approve-plan').disabled=!d.script.trim()&&!chapter().scenes.length};request('/api/plan?chapterId='+encodeURIComponent(chapter().id)).then(result=>{const status=document.querySelector('#plan-status');if(status&&chapter()?.id===result.chapterId&&currentDraft().script===(chapter().script||''))status.textContent=result.approved?'This plan version is approved.':'Plan awaiting approval'}).catch(()=>{});document.querySelector('#save-plan').onclick=()=>save(false);document.querySelector('#approve-plan').onclick=()=>save(true)}
async function save(approve){const c=chapter(),d=currentDraft(),input=document.querySelector('#plan-script'),buttons=[...document.querySelectorAll('.plan-actions button')];input.disabled=true;buttons.forEach(b=>b.disabled=true);try{const latest=await request('/api/state'),remote=latest.project.chapters.find(x=>x.id===c.id);if(!remote)throw Error('This chapter was removed. Your draft is preserved.');if((remote.script||'')!==d.baseScript)throw Error('The saved script changed elsewhere. Your draft is preserved. Open the full editor to compare before saving.');remote.script=d.script;if(remote.studioPlanApproval&&d.script!==(c.script||''))delete remote.studioPlanApproval;studio.state=await post('/api/state',{expectedRevision:latest.revision,project:latest.project},'PUT');if(approve)studio.state=await post('/api/plan/approve',{chapterId:c.id,expectedRevision:studio.state.revision});studio.planDrafts.delete(c.id);emitUI(true);renderWorkspace();notify(approve?'This plan version is approved.':'Draft saved.')}catch(e){notify(e.message);document.querySelector('#plan-status').textContent=e.message;input.disabled=false;buttons.forEach(b=>b.disabled=false)}}

const bookSelections=new Map();
const businessJSON=(id,body)=>rpc('/api/business/'+id,{method:'POST',body:JSON.stringify(body)});
function bindBookSurface(){
 const container=document.querySelector('#book-plan-surface');if(!container)return;
 const key=studio.chapterId||'',selected=bookSelections.get(key)||{},selectors={...(key?{chapterId:key}:{}),...selected};
 for(const key of Object.keys(selectors))if(selectors[key]===null||selectors[key]===undefined)delete selectors[key];
 businessJSON('book.get.v1',selectors).then(result=>{
  if(!container.isConnected)return;container.innerHTML=renderBookPlan(result.plan,result.tempo,{readOnly:studio.readOnly||result.readOnly});
  bindBookPlan(container,result.plan,{readOnly:studio.readOnly||result.readOnly,compose,
   onView:next=>{bookSelections.set(key,next);bindBookSurface();},
   savePatch:body=>{if(studio.readOnly||result.plan.historical)throw Error('Pinned book plan is read only.');return businessJSON('book.patch.v1',{expectedRevision:body.expectedRevision,baseVersion:body.baseVersion,baseSHA256:body.baseSHA256,request:body.request,patchesJson:JSON.stringify(body.patches)});},
   onSaved:async()=>{studio.state=await request('/api/state');bookSelections.delete(key);bindBookSurface();},onError:e=>notify(e.message)});
 }).catch(error=>{if(container.isConnected)container.textContent='Book plan unavailable: '+error.message;});
}
function bindLocationSurface(){
 const container=document.querySelector('#location-reference-surface');if(!container)return;
 const label=document.createElement('label');label.textContent='Location catalog ID ';const input=document.createElement('input');input.maxLength=160;label.append(input);
 const button=document.createElement('button');button.textContent='Find registered references';button.disabled=studio.readOnly;
 const status=document.createElement('p');status.textContent=studio.readOnly?'Location lookup is unavailable in a pinned revision.':'Metadata lookup only. Selecting a reference prepares conversation text; no approval or generation.';
 const results=document.createElement('div');container.replaceChildren(label,button,status,results);
 button.onclick=async()=>{button.disabled=true;try{const result=await businessJSON('location.query.v1',{location:input.value,scope:'approved'});if(!container.isConnected)return;results.replaceChildren();const items=Array.isArray(result.media)?result.media:Array.isArray(result.items)?result.items:[];status.textContent=items.length+' registered references. Geometry underlays and seamless panoramas retain their distinct roles.';for(const item of items.slice(0,64)){const b=document.createElement('button');const id=item.id||item.assetId||item.relativePath;const role=item.role||item.referenceRole||'catalog reference';b.textContent=String(id||'reference')+' · '+String(role);b.onclick=()=>compose('Use location '+input.value+', reference '+String(id||'')+' with semantic role '+String(role)+'. Resolve registered identity and current chapter bindings before any production.');results.append(b);}}catch(e){status.textContent='Location lookup unavailable: '+e.message;}finally{button.disabled=studio.readOnly;}};
}
